// packages/tsdown-plugins/savvy.build.ts
// Escape-hatch self-build: imports buildTargetGroups from this package's OWN ./src
// (no built copy exists yet). tsx compiles the TS on the fly. See spec 3.1.
//
// Meta / forgotten-export check: --target prod calls runMetaPass (api-extractor) via
// the shared helper, mirroring what runBuild does for packages that set meta. This
// emits dist/prod/npm/meta/tsdown-plugins.api.json and copies the model into
// meta.localPaths. ae-*/tsdoc-* warnings that are not yet suppressed appear in the
// rendered report and issues.json but do not fail a local build (only hard errors
// crash; CI escalates ae-forgotten-export to a hard error).
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { Effect } from "effect";
import type { MetaOptions, PublishTargets, RenderedOutput } from "./src/index.js";
import {
	BuildCollector,
	ReportPipelineLive,
	buildTargetGroups,
	defaultManifestTransform,
	packageJsonEntries,
	removeDeclarationMaps,
	renderReport,
	resolveTargets,
	runMetaPass,
	writeIssuesArtifact,
	writeResolvedTsconfig,
	writeTargetsBinding,
} from "./src/index.js";

const cwd = import.meta.dirname;
const pkg = JSON.parse(readFileSync(join(cwd, "package.json"), "utf-8")) as {
	name: string;
	version: string;
	publishConfig?: { targets?: PublishTargets };
	exports?: Record<string, string>;
};
const i = process.argv.indexOf("--target");
const rawTarget = i >= 0 ? process.argv[i + 1] : undefined;
if (rawTarget !== undefined && rawTarget !== "dev" && rawTarget !== "prod") {
	throw new Error(`Unknown --target: ${rawTarget}`);
}
const target = rawTarget ?? "dev";

const collector = new BuildCollector();
const verbose = process.argv.includes("--verbose");

const meta: MetaOptions = {
	localPaths: ["../../website/lib/models/tsdown-plugins"],
	tsdoc: {
		// @since/@category leak from @effect/platform's inlined FileSystem declaration
		// (a devDependency rolled into the bundled .d.ts). We cannot edit upstream comments,
		// so register the tags to silence tsdoc-undefined-tag on those library blocks.
		tagDefinitions: [
			{ tagName: "@since", syntaxKind: "block" },
			{ tagName: "@category", syntaxKind: "block" },
		],
		// The "<Name>_base" synthetics are anonymous base classes generated by Effect's
		// Schema.Class / Context.Tag / Data.TaggedError mixins. They are not real,
		// nameable exports (nothing to export or tag) — a genuine ae-forgotten-export
		// false positive. Pattern is narrow enough to never match a real type.
		suppressWarnings: [{ messageId: "ae-forgotten-export", pattern: "_base" }],
	},
};

const tsconfigPath = writeResolvedTsconfig({ cwd });

try {
	await buildTargetGroups({
		cwd,
		version: pkg.version,
		entry: packageJsonEntries({ cwd }),
		tsconfigPath,
		groups: target === "prod" ? [{ id: "npm", name: pkg.name }] : [{ id: "dev", name: pkg.name }],
		devManifest: "preserve",
		// tsdown/rolldown are type-only imports; keep effect external like the rslib config did.
		// typescript is a runtime dep (tsconfig-resolver uses the TS API); externalize it so the
		// 8 MB compiler is not inlined into the bundle.
		externals: ["effect", "tsdown", "rolldown", "typescript"],
		// Reproduce the rslib config's prod strip.
		transform: defaultManifestTransform,
		...(target === "prod" ? { emitDeclarations: true } : {}),
		collector,
		verbose,
	});

	if (target === "prod") {
		// Emit the dist/prod/targets.json binding the release action consumes — the front
		// door (runBuild) writes this; the escape hatch must too, or the action falls back
		// to a phantom/dev target. Derive the targets from publishConfig.targets (not a
		// hardcoded map) so the binding tracks the manifest.
		const targets = pkg.publishConfig?.targets;
		if (targets === undefined) {
			throw new Error("Missing package.json publishConfig.targets for --target prod");
		}
		writeTargetsBinding(cwd, resolveTargets({ targets, baseName: pkg.name }));
		// Emit the api-model meta bundle and copy it into the local consumer paths.
		// Mirrors what runBuild does for --target prod when meta is configured.
		// Must run BEFORE removeDeclarationMaps: api-extractor needs .d.ts.map files to
		// resolve original-source positions in the api model.
		const ci = process.env.CI === "true" || process.env.GITHUB_ACTIONS === "true";
		await runMetaPass({
			cwd,
			packageName: pkg.name,
			tsconfigPath,
			groups: [{ id: "npm", name: pkg.name }],
			entries: packageJsonEntries({ cwd }),
			exportsMap: pkg.exports,
			meta,
			collector,
			ci,
		});
		// Strip declaration source-maps from the published prod pkg/ AFTER meta. They are
		// emitted for meta generation (api-extractor reads them for original-source positions),
		// but reference .ts sources the tarball does not ship — dead weight that leaks local
		// paths. dev keeps them.
		removeDeclarationMaps(join(cwd, "dist/prod/npm/pkg"));
	}
} finally {
	// Always render the report — even if the build threw — so captured diagnostics are surfaced
	// before the error propagates (parity with the front-door runBuild).
	const rendered = await Effect.runPromise(
		renderReport(collector.snapshot(pkg.name), {
			verbose,
			noColor: process.env.NO_COLOR !== undefined || !process.stdout.isTTY,
		}).pipe(Effect.provide(ReportPipelineLive)),
	);
	for (const out of rendered as ReadonlyArray<RenderedOutput>) process.stdout.write(`${out.content}\n`);
	// Persist the structured diagnostics artifact for every target — matches run.ts:500/505.
	// Best-effort: a write failure must never mask the build outcome.
	try {
		writeIssuesArtifact({ cwd, target, reports: collector.snapshot(pkg.name) });
	} catch {
		// intentionally swallowed
	}
}
