import { build } from "@savvy-web/bundler";
import { PnpmConfigPlugin } from "rolldown-pnpm-config";

await build({
	plugins: [
		PnpmConfigPlugin({
			name: "@savvy-web/pnpm-plugin-silk",
			catalogs: {
				silk: {
					packages: {
						"@effect/ai": {
							range: "^0.36.0",
							peer: "^0.36.0",
							strategy: "interop",
						},
						"@effect/ai-amazon-bedrock": {
							range: "^0.16.1",
							peer: "^0.16.1",
							strategy: "interop",
						},
						"@effect/ai-anthropic": {
							range: "^0.26.0",
							peer: "^0.26.0",
							strategy: "interop",
						},
						"@effect/ai-google": {
							range: "^0.15.0",
							peer: "^0.15.0",
							strategy: "interop",
						},
						"@effect/ai-openai": {
							range: "^0.40.1",
							peer: "^0.40.1",
							strategy: "interop",
						},
						"@effect/cli": {
							range: "^0.75.2",
							peer: "^0.75.2",
							strategy: "interop",
						},
						"@effect/cluster": {
							range: "^0.59.0",
							peer: "^0.59.0",
							strategy: "interop",
						},
						"@effect/experimental": {
							range: "^0.60.0",
							peer: "^0.60.0",
							strategy: "interop",
						},
						"@effect/language-service": {
							range: "^0.86.2",
							peer: "^0.86.2",
							strategy: "interop",
						},
						"@effect/opentelemetry": {
							range: "^0.63.0",
							peer: "^0.63.0",
							strategy: "interop",
						},
						"@effect/platform": {
							range: "^0.96.2",
							peer: "^0.96.0",
							strategy: "interop",
						},
						"@effect/platform-browser": {
							range: "^0.76.0",
							peer: "^0.76.0",
							strategy: "interop",
						},
						"@effect/platform-bun": {
							range: "^0.90.0",
							peer: "^0.90.0",
							strategy: "interop",
						},
						"@effect/platform-node": {
							range: "^0.107.0",
							peer: "^0.107.0",
							strategy: "interop",
						},
						"@effect/platform-node-shared": {
							range: "^0.60.0",
							peer: "^0.60.0",
							strategy: "interop",
						},
						"@effect/printer": {
							range: "^0.49.0",
							peer: "^0.49.0",
							strategy: "interop",
						},
						"@effect/printer-ansi": {
							range: "^0.49.0",
							peer: "^0.49.0",
							strategy: "interop",
						},
						"@effect/rpc": {
							range: "^0.75.1",
							peer: "^0.75.1",
							strategy: "interop",
						},
						"@effect/sql": {
							range: "^0.51.1",
							peer: "^0.51.0",
							strategy: "interop",
						},
						"@effect/sql-clickhouse": {
							range: "^0.49.0",
							peer: "^0.49.0",
							strategy: "interop",
						},
						"@effect/sql-d1": {
							range: "^0.49.0",
							peer: "^0.49.0",
							strategy: "interop",
						},
						"@effect/sql-drizzle": {
							range: "^0.50.0",
							peer: "^0.50.0",
							strategy: "interop",
						},
						"@effect/sql-kysely": {
							range: "^0.47.0",
							peer: "^0.47.0",
							strategy: "interop",
						},
						"@effect/sql-libsql": {
							range: "^0.41.0",
							peer: "^0.41.0",
							strategy: "interop",
						},
						"@effect/sql-mssql": {
							range: "^0.52.0",
							peer: "^0.52.0",
							strategy: "interop",
						},
						"@effect/sql-mysql2": {
							range: "^0.52.0",
							peer: "^0.52.0",
							strategy: "interop",
						},
						"@effect/sql-pg": {
							range: "^0.52.1",
							peer: "^0.52.1",
							strategy: "interop",
						},
						"@effect/sql-sqlite-bun": {
							range: "^0.52.0",
							peer: "^0.52.0",
							strategy: "interop",
						},
						"@effect/sql-sqlite-do": {
							range: "^0.29.0",
							peer: "^0.29.0",
							strategy: "interop",
						},
						"@effect/sql-sqlite-node": {
							range: "^0.52.0",
							peer: "^0.52.0",
							strategy: "interop",
						},
						"@effect/sql-sqlite-react-native": {
							range: "^0.54.0",
							peer: "^0.54.0",
							strategy: "interop",
						},
						"@effect/sql-sqlite-wasm": {
							range: "^0.52.0",
							peer: "^0.52.0",
							strategy: "interop",
						},
						"@effect/tsgo": {
							range: "^0.15.0",
							peer: "^0.15.0",
							strategy: "interop",
						},
						"@effect/typeclass": {
							range: "^0.40.0",
							peer: "^0.40.0",
							strategy: "interop",
						},
						"@effect/vitest": {
							range: "^0.29.0",
							peer: "^0.29.0",
							strategy: "interop",
						},
						"@effect/workflow": {
							range: "^0.18.2",
							peer: "^0.18.2",
							strategy: "interop",
						},
						"@types/node": {
							range: "^26.1.0",
							peer: "^26.1.0",
							strategy: "lock-minor",
						},
						"@types/react": {
							range: "^19.2.17",
							peer: "^19.2.0",
							strategy: "lock-minor",
						},
						"@types/react-dom": {
							range: "^19.2.3",
							peer: "^19.2.0",
							strategy: "lock-minor",
						},
						"@typescript/native-preview": {
							range: "^7.0.0-dev.20260630.1",
							peer: "^7.0.0-dev.20260612.1",
						},
						"@vitest/coverage-istanbul": {
							range: "^4.1.9",
							peer: "^4.1.0",
							strategy: "lock-minor",
						},
						"@vitest/coverage-v8": {
							range: "^4.1.9",
							peer: "^4.1.0",
							strategy: "lock-minor",
						},
						effect: {
							range: "^3.21.4",
							peer: "^3.21.0",
							strategy: "interop",
						},
						react: {
							range: "^19.2.7",
							peer: "^19.2.0",
							strategy: "lock-minor",
						},
						"react-dom": {
							range: "^19.2.7",
							peer: "^19.2.0",
							strategy: "lock-minor",
						},
						tsx: {
							range: "^4.22.4",
							peer: "^4.22.4",
							strategy: "lock",
						},
						typescript: {
							range: "^6.0.3",
							peer: "^6.0.0",
							strategy: "lock-minor",
						},
						vitest: {
							range: "^4.1.9",
							peer: "^4.1.0",
							strategy: "lock-minor",
						},
					},
				},
			},
			confirmModulesPurge: false,
			minimumReleaseAge: 1440,
			minimumReleaseAgeExclude: [
				"@savvy-web/*",
				"@vitest-agent/*",
				"@typescript/*",
				"@spencerbeggs/*",
				"vitest-bats",
				"rspress-plugin-api-extractor",
				"runtime-resolver",
				"reposets",
				"type-registry-effect",
				"semver-effect",
				"workspaces-effect",
				"yaml-effect",
				"jsonc-effect",
				"json-schema-effect",
				"package-json-effect",
				"config-file-effect",
				"rolldown-pnpm-config",
				"std-osc8",
				"api-extractor-llms",
				"xdg-effect",
			],
			overrides: {
				"@manypkg/find-root>@types/node": "catalog:silk",
			},
			publicHoistPattern: {
				excludeByRepo: {
					"savvy-web-systems": ["@savvy-web/cli", "@savvy-web/mcp"],
					"vitest-agent": ["@vitest-agent/cli", "@vitest-agent/mcp"],
				},
				value: [
					"@changesets/cli",
					"@commitlint/cli",
					"@commitlint/config-conventional",
					"@commitlint/cz-commitlint",
					"@rslib/core",
					"@savvy-web/cli",
					"@savvy-web/mcp",
					"@types/bun",
					"@types/node",
					"@types/react",
					"@types/react-dom",
					"@typescript/native-preview",
					"@vitest-agent/cli",
					"@vitest-agent/mcp",
					"@vitest/coverage-istanbul",
					"@vitest/coverage-v8",
					"commitizen",
					"husky",
					"lint-staged",
					"markdownlint-cli2",
					"markdownlint-cli2-formatter-codequality",
					"tsx",
					"turbo",
					"typescript",
					"vitest",
				],
			},
			allowBuilds: {
				"@parcel/watcher": true,
				"better-sqlite3": true,
				"core-js": true,
				esbuild: true,
				"msgpackr-extract": true,
			},
			allowedDeprecatedVersions: {
				glob: "*",
				inflight: "*",
				"prebuild-install": "*",
				"@types/acorn": "*",
				"git-raw-commits": "*",
				"node-domexception": "*",
			},
			strictDepBuilds: true,
			blockExoticSubdeps: true,
			peerDependencyRules: {
				allowedVersions: {
					"@effect/vitest>vitest": "^4.1.0",
					"@typescript-eslint/project-service>typescript": "^6.0.0",
					"@typescript-eslint/tsconfig-utils>typescript": "^6.0.0",
					"@typescript-eslint/typescript-estree>typescript": "^6.0.0",
					"@typescript-eslint/util>typescript": "^6.0.0",
					"@typescript-eslint/utils>typescript": "^6.0.0",
					"eslint-plugin-tsdoc>typescript": "^6.0.0",
					"ink-tab>ink": "^7.0.0",
				},
			},
		}),
	],
	bundleNodeModules: true,
	looseFiles: {
		"pnpmfile.mjs": "./src/pnpmfile.ts",
		"pnpmfile.cjs": "./src/pnpmfile.ts",
	},
});
