/**
 * Init command - bootstrap lint-staged configuration.
 *
 * @internal
 */
import { chmod } from "node:fs/promises";
import { dirname } from "node:path";
import { isDeepStrictEqual } from "node:util";
import type { JsoncFormattingOptions } from "@effected/jsonc";
import { Jsonc, JsoncEdit, JsoncModifier } from "@effected/jsonc";
import type { SectionFileError, SectionParseError, SectionRenderError } from "@effected/templates";
import { ManagedSection } from "@effected/templates";
import { WorkspaceDiscovery } from "@effected/workspaces";
import {
	BiomeSchemaSync,
	Lint,
	SavvyBaseSection,
	SavvyHooksSection,
	SavvyToolchainSection,
	savvyBasePreamble,
	savvyHooksHygiene,
	savvyToolchainCheck,
} from "@savvy-web/silk-effects";
import { Effect, FileSystem } from "effect";
import type { PlatformError } from "effect/PlatformError";
import { BIOME_VERSION } from "./biome-version.js";

/** Unicode checkmark symbol. */
const CHECK_MARK = "✓";

/** Unicode warning symbol. */
const WARNING = "⚠";

/** Executable file permission mode. */
const EXECUTABLE_MODE = 0o755;

/** Formatting options for jsonc-effect surgical edits. */
const JSONC_FORMAT: Partial<JsoncFormattingOptions> = { tabSize: 1, insertSpaces: false };

/** Available presets. */
type PresetType = "minimal" | "standard" | "silk";

/** Header written when creating a fresh pre-commit hook. */
const PRE_COMMIT_HEADER =
	"#!/usr/bin/env sh\n# Pre-commit hook with savvy managed sections\n# Custom hooks can go above, below, or between the managed sections\n\n";

/** Header written when creating a fresh hygiene hook (post-checkout / post-merge / post-commit). */
const HYGIENE_HEADER =
	"#!/usr/bin/env sh\n# Managed by savvy-hooks\n# Custom hooks can go above or below the managed section\n\n";

/**
 * Check if a preset includes the ShellScripts handler.
 *
 * @param preset - The preset to check
 * @returns True if the preset includes ShellScripts (standard and silk)
 */
function presetIncludesShellScripts(preset: PresetType): boolean {
	return preset !== "minimal";
}

/**
 * Check if a preset includes markdown tooling.
 *
 * @param preset - The preset to check
 * @returns True if the preset includes Markdown (standard and silk)
 */
function presetIncludesMarkdown(preset: PresetType): boolean {
	return preset !== "minimal";
}

/**
 * Generate the lint-staged config file content.
 *
 * @param preset - The preset to use
 * @returns Config file content
 */
function generateConfigContent(preset: PresetType): string {
	return `/**
 * lint-staged configuration
 * Generated by savvy lint init
 */
import { Preset } from "@savvy-web/silk/lint";

export default Preset.${preset}();
`;
}

/**
 * Write or update the markdownlint-cli2 config file.
 *
 * @param fs - FileSystem service
 * @param preset - The active preset
 * @param force - Whether to overwrite the entire file
 * @returns Effect that manages the markdownlint config
 */
function writeMarkdownlintConfig(fs: FileSystem.FileSystem, preset: PresetType, force: boolean) {
	return Effect.gen(function* () {
		const configExists = yield* fs.exists(Lint.MARKDOWNLINT_CONFIG_PATH);
		const fullTemplate = JSON.stringify(Lint.MARKDOWNLINT_TEMPLATE, null, "\t");

		if (!configExists) {
			// File missing → write full template
			yield* fs.makeDirectory("lib/configs", { recursive: true });
			yield* fs.writeFileString(Lint.MARKDOWNLINT_CONFIG_PATH, `${fullTemplate}\n`);
			yield* Effect.log(`${CHECK_MARK} Created ${Lint.MARKDOWNLINT_CONFIG_PATH}`);
			return;
		}

		if (preset !== "silk") {
			// Standard preset: don't manage existing files
			yield* Effect.log(`${CHECK_MARK} ${Lint.MARKDOWNLINT_CONFIG_PATH}: exists (not managed by ${preset} preset)`);
			return;
		}

		if (force) {
			// Force: overwrite entire file with fresh template
			yield* fs.writeFileString(Lint.MARKDOWNLINT_CONFIG_PATH, `${fullTemplate}\n`);
			yield* Effect.log(`${CHECK_MARK} Replaced ${Lint.MARKDOWNLINT_CONFIG_PATH} (--force)`);
			return;
		}

		// Silk preset, no force: surgical management of $schema + ignores; config
		// is compared but only warned on (it may carry intentional local rule
		// overrides). $schema and ignores are safe to apply automatically.
		const existingText = yield* fs.readFileString(Lint.MARKDOWNLINT_CONFIG_PATH);
		const existingParsed = (yield* Jsonc.parse(existingText)) as Record<string, unknown>;

		let updatedText = existingText;
		const applied: string[] = [];

		// Always update $schema silently
		if (existingParsed.$schema !== Lint.MARKDOWNLINT_SCHEMA) {
			const edits = yield* JsoncModifier.modify(updatedText, ["$schema"], Lint.MARKDOWNLINT_SCHEMA, {
				formattingOptions: JSONC_FORMAT,
			});
			updatedText = JsoncEdit.applyAll(updatedText, edits);
			applied.push("$schema");
		}

		// Non-destructively union-merge template ignores into the existing list.
		// ignores are additive safety-excludes — appending the defaults a repo is
		// missing can't flip any lint verdict — so unlike config rules we apply
		// them automatically while preserving any user-added entries and order.
		const existingIgnores = Array.isArray(existingParsed.ignores) ? (existingParsed.ignores as string[]) : [];
		const missingIgnores = Lint.MARKDOWNLINT_TEMPLATE.ignores.filter((glob) => !existingIgnores.includes(glob));
		if (missingIgnores.length > 0) {
			const mergedIgnores = [...existingIgnores, ...missingIgnores];
			const edits = yield* JsoncModifier.modify(updatedText, ["ignores"], mergedIgnores, {
				formattingOptions: JSONC_FORMAT,
			});
			updatedText = JsoncEdit.applyAll(updatedText, edits);
			applied.push(`ignores (+${missingIgnores.length})`);
		}

		// Compare config with isDeepStrictEqual (warn-only — never auto-written)
		const existingConfig = existingParsed.config as Record<string, unknown> | undefined;
		const configMatches = existingConfig !== undefined && isDeepStrictEqual(existingConfig, Lint.MARKDOWNLINT_CONFIG);
		if (!configMatches) {
			yield* Effect.log(
				`${WARNING} ${Lint.MARKDOWNLINT_CONFIG_PATH}: config rules differ from template (use --force to overwrite)`,
			);
		}

		if (applied.length > 0) {
			yield* fs.writeFileString(Lint.MARKDOWNLINT_CONFIG_PATH, updatedText);
			yield* Effect.log(`${CHECK_MARK} Updated ${applied.join(", ")} in ${Lint.MARKDOWNLINT_CONFIG_PATH}`);
		} else if (configMatches) {
			yield* Effect.log(`${CHECK_MARK} ${Lint.MARKDOWNLINT_CONFIG_PATH}: up-to-date`);
		}
	});
}

/**
 * Every directory a biome config may sit in: the workspace root plus each leaf
 * package the workspace `packages:` patterns enumerate.
 *
 * @remarks
 * `BiomeSchemaSync` scans a single directory per call, so a monorepo needs the
 * roots enumerated up front. `listPackages` already includes the workspace root
 * itself (the entry whose `relativePath` is `"."`), so no extra cwd pass is
 * needed on the happy path.
 *
 * Discovery failing yields an EMPTY list, which the caller reads as "no roots
 * to enumerate — scan `BiomeSchemaSync`'s own default directory instead". The
 * cwd is deliberately not named here: resolving it is the sync service's job,
 * and an ambient `process.cwd()` read in this function would be a second,
 * divergent source of truth for the same directory.
 *
 * The two ways discovery fails mean different things and are reported differently:
 *
 * - `WorkspaceRootNotFoundError` is the normal shape of a plain single-package
 *   project (no `pnpm-workspace.yaml`, no `workspaces` field). Nothing to say.
 * - Anything else (an unenumerable `packages:` pattern, a leaf manifest missing
 *   a `version`) means leaves exist but could not be enumerated, so the fallback
 *   silently under-scans. That earns a warning.
 *
 * @returns Effect yielding the directories to scan, never failing
 */
function biomeConfigRoots(): Effect.Effect<ReadonlyArray<string>, never, WorkspaceDiscovery> {
	return Effect.gen(function* () {
		const discovery = yield* WorkspaceDiscovery;
		return yield* discovery.listPackages().pipe(
			Effect.map((packages) => packages.map((pkg) => pkg.path)),
			Effect.catchTag("WorkspaceRootNotFoundError", () => Effect.succeed<ReadonlyArray<string>>([])),
			Effect.catch((e) =>
				Effect.as(Effect.log(`${WARNING} Only syncing biome $schema in the current directory: ${e.message}`), []),
			),
		);
	});
}

/**
 * Find and sync biome config `$schema` URLs to match the pinned {@link BIOME_VERSION}.
 *
 * @remarks
 * Covers every workspace root, not just the repository root: a leaf package
 * carrying its own `biome.json`/`biome.jsonc` is updated in the same pass.
 * A failure on one root is reported and skipped rather than aborting the rest,
 * so one unreadable or malformed config cannot strand the others on a stale
 * schema URL.
 *
 * Exported for the handler tests, which drive this seam over an in-memory
 * volume — `runLintInit` itself chmods hook files through `node:fs/promises`,
 * which no `FileSystem` double can intercept.
 *
 * @returns Effect that syncs biome schemas and logs results
 *
 * @internal
 */
export function syncBiomeSchemas(): Effect.Effect<void, never, BiomeSchemaSync | WorkspaceDiscovery> {
	return Effect.gen(function* () {
		const syncer = yield* BiomeSchemaSync;
		const roots = yield* biomeConfigRoots();

		// An empty root list means discovery could not enumerate one; fall through
		// to a single pass over `BiomeSchemaSync`'s own default directory.
		const passes: ReadonlyArray<{ cwd: string } | undefined> =
			roots.length > 0 ? roots.map((cwd) => ({ cwd })) : [undefined];

		for (const options of passes) {
			yield* syncer.sync(BIOME_VERSION, options).pipe(
				Effect.flatMap((result) =>
					Effect.gen(function* () {
						for (const configPath of result.current) {
							yield* Effect.log(`${CHECK_MARK} ${configPath}: biome $schema up-to-date`);
						}
						for (const configPath of result.updated) {
							yield* Effect.log(`${CHECK_MARK} Updated $schema in ${configPath}`);
						}
					}),
				),
				Effect.catchTag("BiomeSyncError", (e) => Effect.log(`${WARNING} Could not sync biome $schema: ${e.message}`)),
			);
		}
	});
}

/** Make a file executable. */
function makeExecutable(path: string) {
	return Effect.tryPromise({
		try: () => chmod(path, EXECUTABLE_MODE),
		catch: (e) => new Error(String(e)),
	});
}

/** Ensure a hook file exists, writing `header` if it does not. */
function ensureHookFile(path: string, header: string) {
	return Effect.gen(function* () {
		const fs = yield* FileSystem.FileSystem;
		const exists = yield* fs.exists(path);
		if (!exists) {
			yield* fs.writeFileString(path, header);
		}
	});
}

/**
 * Run the full lint init pipeline.
 *
 * Exported so Task B5's unified `savvy init` orchestrator can invoke the
 * lint-staged init step directly without going through the CLI command layer.
 *
 * @param opts - The same options the CLI command receives
 * @returns An Effect that performs initialization
 *
 * @internal
 */
export function runLintInit(opts: {
	force: boolean;
	config: string;
	preset: "minimal" | "standard" | "silk";
}): Effect.Effect<
	void,
	Error | SectionParseError | SectionRenderError | SectionFileError | PlatformError,
	ManagedSection | FileSystem.FileSystem | BiomeSchemaSync | WorkspaceDiscovery
> {
	const { force, config, preset } = opts;
	return Effect.gen(function* () {
		const fs = yield* FileSystem.FileSystem;
		const ms = yield* ManagedSection;

		if (config.startsWith("/")) {
			yield* Effect.fail(new Error("Config path must be relative to repository root, not absolute"));
		}

		yield* Effect.log("Initializing lint-staged configuration...\n");

		yield* fs.makeDirectory(".husky", { recursive: true });

		// pre-commit: savvy-base preamble then savvy-lint tool section, in order.
		if (force) {
			yield* fs.writeFileString(Lint.HUSKY_HOOK_PATH, PRE_COMMIT_HEADER);
		} else {
			yield* ensureHookFile(Lint.HUSKY_HOOK_PATH, PRE_COMMIT_HEADER);
		}
		const preCommitResults = yield* ms.syncAll(Lint.HUSKY_HOOK_PATH, [
			SavvyBaseSection.section(savvyBasePreamble()),
			Lint.savvyLintBlock(config),
		]);
		yield* makeExecutable(Lint.HUSKY_HOOK_PATH);
		yield* Effect.log(
			`${CHECK_MARK} ${force ? "Replaced" : "Synced"} ${Lint.HUSKY_HOOK_PATH} (${preCommitResults
				.map((r) => r._tag)
				.join(", ")})`,
		);

		// post-checkout / post-merge / post-commit: co-owned savvy-hooks hygiene (when preset enables it).
		// post-checkout and post-merge additionally carry the savvy-toolchain drift check —
		// they fire exactly when a pin bump or branch switch can make the local package
		// manager stale. post-commit does not: it fires on every commit, which is noisier
		// than the drift warrants.
		if (presetIncludesShellScripts(preset)) {
			for (const hookPath of [Lint.POST_CHECKOUT_HOOK_PATH, Lint.POST_MERGE_HOOK_PATH, Lint.POST_COMMIT_HOOK_PATH]) {
				yield* ensureHookFile(hookPath, HYGIENE_HEADER);
				// Migrate legacy SAVVY-LINT hygiene section if present.
				yield* ms.remove(hookPath, Lint.LegacySavvyLintHygieneDef);
				const sections = [SavvyHooksSection.section(savvyHooksHygiene())];
				if (hookPath !== Lint.POST_COMMIT_HOOK_PATH) {
					sections.push(SavvyToolchainSection.section(savvyToolchainCheck()));
				}
				yield* ms.syncAll(hookPath, sections);
				yield* makeExecutable(hookPath);
				yield* Effect.log(`${CHECK_MARK} Synced ${hookPath}`);
			}
		}

		// Write markdownlint config (when preset includes Markdown)
		if (presetIncludesMarkdown(preset)) {
			yield* writeMarkdownlintConfig(fs, preset, force);
		}

		// Sync biome $schema URLs across every workspace root
		yield* syncBiomeSchemas();

		// Handle config file
		const configExists = yield* fs.exists(config);

		if (configExists && !force) {
			yield* Effect.log(`${WARNING} ${config} already exists (use --force to overwrite)`);
		} else {
			const configDir = dirname(config);
			if (configDir && configDir !== ".") {
				yield* fs.makeDirectory(configDir, { recursive: true });
			}
			yield* fs.writeFileString(config, generateConfigContent(preset));
			yield* Effect.log(`${CHECK_MARK} Created ${config} (preset: ${preset})`);
		}

		yield* Effect.log("\nDone! Lint-staged is ready to use.");
	});
}
