/**
 * Init command - bootstrap lint-staged configuration.
 *
 * @internal
 */
import { chmod } from "node:fs/promises";
import { dirname } from "node:path";
import { isDeepStrictEqual } from "node:util";
import { Command, Options } from "@effect/cli";
import { FileSystem } from "@effect/platform";
import type { PlatformError } from "@effect/platform/Error";
import type { SectionWriteError } from "@savvy-web/silk-effects";
import {
	BiomeSchemaSync,
	Lint,
	ManagedSection,
	SavvyBaseSection,
	SavvyHooksSection,
	savvyBasePreamble,
	savvyHooksHygiene,
} from "@savvy-web/silk-effects";
import { Effect } from "effect";
import type { JsoncFormattingOptions } from "jsonc-effect";
import { applyEdits, modify, parse } from "jsonc-effect";

/** Unicode checkmark symbol. */
const CHECK_MARK = "✓";

/** Unicode warning symbol. */
const WARNING = "⚠";

/** Executable file permission mode. */
const EXECUTABLE_MODE = 0o755;

/** Formatting options for jsonc-effect surgical edits. */
const JSONC_FORMAT: Partial<JsoncFormattingOptions> = { tabSize: 1, insertSpaces: false };

/** Available presets. */
type PresetType = "minimal" | "standard" | "silk";

/** Header written when creating a fresh pre-commit hook. */
const PRE_COMMIT_HEADER =
	"#!/usr/bin/env sh\n# Pre-commit hook with savvy managed sections\n# Custom hooks can go above, below, or between the managed sections\n\n";

/** Header written when creating a fresh hygiene hook (post-checkout / post-merge / post-commit). */
const HYGIENE_HEADER =
	"#!/usr/bin/env sh\n# Managed by savvy-hooks\n# Custom hooks can go above or below the managed section\n\n";

/**
 * Check if a preset includes the ShellScripts handler.
 *
 * @param preset - The preset to check
 * @returns True if the preset includes ShellScripts (standard and silk)
 */
function presetIncludesShellScripts(preset: PresetType): boolean {
	return preset !== "minimal";
}

/**
 * Check if a preset includes markdown tooling.
 *
 * @param preset - The preset to check
 * @returns True if the preset includes Markdown (standard and silk)
 */
function presetIncludesMarkdown(preset: PresetType): boolean {
	return preset !== "minimal";
}

/**
 * Generate the lint-staged config file content.
 *
 * @param preset - The preset to use
 * @returns Config file content
 */
function generateConfigContent(preset: PresetType): string {
	return `/**
 * lint-staged configuration
 * Generated by savvy lint init
 */
import { Preset } from "@savvy-web/silk/lint";

export default Preset.${preset}();
`;
}

/**
 * Write or update the markdownlint-cli2 config file.
 *
 * @param fs - FileSystem service
 * @param preset - The active preset
 * @param force - Whether to overwrite the entire file
 * @returns Effect that manages the markdownlint config
 */
function writeMarkdownlintConfig(fs: FileSystem.FileSystem, preset: PresetType, force: boolean) {
	return Effect.gen(function* () {
		const configExists = yield* fs.exists(Lint.MARKDOWNLINT_CONFIG_PATH);
		const fullTemplate = JSON.stringify(Lint.MARKDOWNLINT_TEMPLATE, null, "\t");

		if (!configExists) {
			// File missing → write full template
			yield* fs.makeDirectory("lib/configs", { recursive: true });
			yield* fs.writeFileString(Lint.MARKDOWNLINT_CONFIG_PATH, `${fullTemplate}\n`);
			yield* Effect.log(`${CHECK_MARK} Created ${Lint.MARKDOWNLINT_CONFIG_PATH}`);
			return;
		}

		if (preset !== "silk") {
			// Standard preset: don't manage existing files
			yield* Effect.log(`${CHECK_MARK} ${Lint.MARKDOWNLINT_CONFIG_PATH}: exists (not managed by ${preset} preset)`);
			return;
		}

		if (force) {
			// Force: overwrite entire file with fresh template
			yield* fs.writeFileString(Lint.MARKDOWNLINT_CONFIG_PATH, `${fullTemplate}\n`);
			yield* Effect.log(`${CHECK_MARK} Replaced ${Lint.MARKDOWNLINT_CONFIG_PATH} (--force)`);
			return;
		}

		// Silk preset, no force: surgical management of $schema + config
		const existingText = yield* fs.readFileString(Lint.MARKDOWNLINT_CONFIG_PATH);
		const existingParsed = (yield* parse(existingText)) as Record<string, unknown>;

		let updatedText = existingText;
		let schemaUpdated = false;

		// Always update $schema silently
		if (existingParsed.$schema !== Lint.MARKDOWNLINT_SCHEMA) {
			const edits = yield* modify(updatedText, ["$schema"], Lint.MARKDOWNLINT_SCHEMA, {
				formattingOptions: JSONC_FORMAT,
			});
			updatedText = yield* applyEdits(updatedText, edits);
			schemaUpdated = true;
		}

		// Compare config with isDeepStrictEqual
		const existingConfig = existingParsed.config as Record<string, unknown> | undefined;
		const configMatches = existingConfig !== undefined && isDeepStrictEqual(existingConfig, Lint.MARKDOWNLINT_CONFIG);

		if (!configMatches) {
			yield* Effect.log(
				`${WARNING} ${Lint.MARKDOWNLINT_CONFIG_PATH}: config rules differ from template (use --force to overwrite)`,
			);
			// Still write schema update if it changed
			if (schemaUpdated) {
				yield* fs.writeFileString(Lint.MARKDOWNLINT_CONFIG_PATH, updatedText);
				yield* Effect.log(`${CHECK_MARK} Updated $schema in ${Lint.MARKDOWNLINT_CONFIG_PATH}`);
			}
			return;
		}

		if (schemaUpdated) {
			yield* fs.writeFileString(Lint.MARKDOWNLINT_CONFIG_PATH, updatedText);
			yield* Effect.log(`${CHECK_MARK} Updated $schema in ${Lint.MARKDOWNLINT_CONFIG_PATH}`);
		} else {
			yield* Effect.log(`${CHECK_MARK} ${Lint.MARKDOWNLINT_CONFIG_PATH}: up-to-date`);
		}
	});
}

/**
 * Find and sync biome config `$schema` URLs to match the peer dependency version.
 *
 * @returns Effect that syncs biome schemas and logs results
 */
function syncBiomeSchemas() {
	return Effect.gen(function* () {
		const version = process.env.__BIOME_PEER_VERSION__;
		if (!version) return;

		const syncer = yield* BiomeSchemaSync;
		const result = yield* syncer.sync(version);

		for (const configPath of result.current) {
			yield* Effect.log(`${CHECK_MARK} ${configPath}: biome $schema up-to-date`);
		}
		for (const configPath of result.updated) {
			yield* Effect.log(`${CHECK_MARK} Updated $schema in ${configPath}`);
		}
	});
}

/* v8 ignore start -- CLI option definitions; handler tested individually */
const forceOption = Options.boolean("force").pipe(
	Options.withAlias("f"),
	Options.withDescription(
		"Overwrite the pre-commit hook and config file entirely (managed sections in post-checkout/post-merge/post-commit are never force-reset)",
	),
	Options.withDefault(false),
);

const configOption = Options.text("config").pipe(
	Options.withAlias("c"),
	Options.withDescription("Relative path for the lint-staged config file (from repo root)"),
	Options.withDefault(Lint.DEFAULT_CONFIG_PATH),
);

const presetOption = Options.choice("preset", ["minimal", "standard", "silk"]).pipe(
	Options.withAlias("p"),
	Options.withDescription("Preset to use: minimal, standard, or silk"),
	Options.withDefault("silk" as const),
);
/* v8 ignore stop */

/** Make a file executable. */
function makeExecutable(path: string) {
	return Effect.tryPromise({
		try: () => chmod(path, EXECUTABLE_MODE),
		catch: (e) => new Error(String(e)),
	});
}

/** Ensure a hook file exists, writing `header` if it does not. */
function ensureHookFile(path: string, header: string) {
	return Effect.gen(function* () {
		const fs = yield* FileSystem.FileSystem;
		const exists = yield* fs.exists(path);
		if (!exists) {
			yield* fs.writeFileString(path, header);
		}
	});
}

/**
 * Run the full lint init pipeline.
 *
 * Exported so Task B5's unified `savvy init` orchestrator can invoke the
 * lint-staged init step directly without going through the CLI command layer.
 *
 * @param opts - The same options the CLI command receives
 * @returns An Effect that performs initialization
 *
 * @internal
 */
export function runLintInit(opts: {
	force: boolean;
	config: string;
	preset: "minimal" | "standard" | "silk";
}): Effect.Effect<
	void,
	Error | SectionWriteError | PlatformError,
	ManagedSection | FileSystem.FileSystem | BiomeSchemaSync
> {
	const { force, config, preset } = opts;
	return Effect.gen(function* () {
		const fs = yield* FileSystem.FileSystem;
		const ms = yield* ManagedSection;

		if (config.startsWith("/")) {
			yield* Effect.fail(new Error("Config path must be relative to repository root, not absolute"));
		}

		yield* Effect.log("Initializing lint-staged configuration...\n");

		yield* fs.makeDirectory(".husky", { recursive: true });

		// pre-commit: savvy-base preamble then savvy-lint tool section, in order.
		if (force) {
			yield* fs.writeFileString(Lint.HUSKY_HOOK_PATH, PRE_COMMIT_HEADER);
		} else {
			yield* ensureHookFile(Lint.HUSKY_HOOK_PATH, PRE_COMMIT_HEADER);
		}
		const preCommitResults = yield* ms.syncMany(Lint.HUSKY_HOOK_PATH, [
			SavvyBaseSection.block(savvyBasePreamble()),
			Lint.savvyLintBlock(config),
		]);
		yield* makeExecutable(Lint.HUSKY_HOOK_PATH);
		yield* Effect.log(
			`${CHECK_MARK} ${force ? "Replaced" : "Synced"} ${Lint.HUSKY_HOOK_PATH} (${preCommitResults
				.map((r) => r._tag)
				.join(", ")})`,
		);

		// post-checkout / post-merge / post-commit: co-owned savvy-hooks hygiene (when preset enables it).
		if (presetIncludesShellScripts(preset)) {
			for (const hookPath of [Lint.POST_CHECKOUT_HOOK_PATH, Lint.POST_MERGE_HOOK_PATH, Lint.POST_COMMIT_HOOK_PATH]) {
				yield* ensureHookFile(hookPath, HYGIENE_HEADER);
				// Migrate legacy SAVVY-LINT hygiene section if present.
				yield* ms.remove(hookPath, Lint.LegacySavvyLintHygieneDef);
				yield* ms.sync(hookPath, SavvyHooksSection.block(savvyHooksHygiene()));
				yield* makeExecutable(hookPath);
				yield* Effect.log(`${CHECK_MARK} Synced ${hookPath}`);
			}
		}

		// Write markdownlint config (when preset includes Markdown)
		if (presetIncludesMarkdown(preset)) {
			yield* writeMarkdownlintConfig(fs, preset, force);
		}

		// Sync biome $schema URLs
		yield* syncBiomeSchemas().pipe(
			Effect.catchTag("BiomeSyncError", (e) => Effect.log(`${WARNING} Could not sync biome $schema: ${e.message}`)),
		);

		// Handle config file
		const configExists = yield* fs.exists(config);

		if (configExists && !force) {
			yield* Effect.log(`${WARNING} ${config} already exists (use --force to overwrite)`);
		} else {
			const configDir = dirname(config);
			if (configDir && configDir !== ".") {
				yield* fs.makeDirectory(configDir, { recursive: true });
			}
			yield* fs.writeFileString(config, generateConfigContent(preset));
			yield* Effect.log(`${CHECK_MARK} Created ${config} (preset: ${preset})`);
		}

		yield* Effect.log("\nDone! Lint-staged is ready to use.");
	});
}

/**
 * Init command implementation.
 *
 * @remarks
 * Writes:
 * - `.husky/pre-commit` — `savvy-base` preamble + `savvy-lint` tool section, in order
 *   (via `ManagedSection.syncMany`).
 * - `.husky/post-checkout`, `.husky/post-merge`, and `.husky/post-commit` — co-owned
 *   `savvy-hooks` hygiene (idempotent, shared with `@savvy-web/commitlint`). Migrates
 *   legacy `SAVVY-LINT` hygiene blocks by removing them before writing the new section.
 * - `lib/configs/.markdownlint-cli2.jsonc` config (when preset includes Markdown).
 * - lint-staged config at the specified path.
 *
 * Users may add custom commands above, below, or between the managed sections.
 * `--force` resets only the pre-commit hook and the config file; the hygiene sections
 * are always reconciled with `sync`.
 */
/* v8 ignore next 3 -- CLI registration; handler tested via runLintInit */
export const initCommand = Command.make(
	"init",
	{ force: forceOption, config: configOption, preset: presetOption },
	(opts) => runLintInit(opts),
).pipe(Command.withDescription("Initialize lint-staged configuration and husky hooks"));
