/**
 * Effect Schemas for commitlint configuration options.
 *
 * @internal
 */
import { Effect, Schema } from "effect";

/**
 * Release format type for the release commit type.
 *
 * @remarks
 * Determines how release commits are formatted based on versioning strategy:
 * - `semver`: `release: v1.2.3` (for single/fixed-group versioning)
 * - `packages`: `release: version packages` (for independent versioning)
 * - `scoped`: `release(pkg): v1.2.3` (for per-package releases)
 *
 * @public
 */
export type ReleaseFormat = "semver" | "packages" | "scoped";

/**
 * Effect Schema for {@link ReleaseFormat}.
 *
 * @internal
 */
export const ReleaseFormatSchema = Schema.Literals(["semver", "packages", "scoped"]);

/**
 * Effect Schema for validating {@link ConfigOptions}.
 *
 * @remarks
 * This schema validates and applies defaults to user-provided configuration.
 * Used internally by {@link CommitlintConfig.silk} via {@link decodeConfigOptions}.
 *
 * @internal
 */
export const ConfigOptionsSchema = Schema.Struct({
	dco: Schema.optional(Schema.Boolean),
	scopes: Schema.optional(Schema.Array(Schema.String)),
	additionalScopes: Schema.optional(Schema.Array(Schema.String)),
	releaseFormat: Schema.optional(ReleaseFormatSchema),
	emojis: Schema.Boolean.pipe(Schema.withDecodingDefaultType(Effect.succeed(false))),
	bodyMaxLineLength: Schema.Number.check(Schema.isGreaterThan(0)).pipe(
		Schema.withDecodingDefaultType(Effect.succeed(300)),
	),
	noMarkdown: Schema.Boolean.pipe(Schema.withDecodingDefaultType(Effect.succeed(true))),
	cwd: Schema.optional(Schema.String),
});

/**
 * Decode unknown input into {@link ResolvedConfigOptions}, applying defaults.
 *
 * @remarks
 * Synchronous decoder that throws a `ParseError` on invalid input, mirroring
 * the previous Zod `.parse()` contract used by {@link CommitlintConfig.silk}.
 *
 * @internal
 */
export const decodeConfigOptions = Schema.decodeUnknownSync(ConfigOptionsSchema);

/**
 * Configuration options for {@link CommitlintConfig.silk}.
 *
 * @remarks
 * All properties are optional. When omitted, values are auto-detected
 * from the repository structure or use sensible defaults.
 *
 * @public
 */
export interface ConfigOptions {
	/**
	 * Enable DCO signoff requirement.
	 *
	 * @remarks
	 * - `true`: Always require signoff
	 * - `false`: Never require signoff
	 * - `undefined`: Auto-detect from DCO file presence
	 *
	 * @defaultValue Auto-detected
	 */
	dco?: boolean;

	/**
	 * Allowed scopes for commits.
	 *
	 * @remarks
	 * When provided, enforces a `scope-enum` rule restricting commits
	 * to only these scopes. When omitted, any scope is allowed.
	 *
	 * @defaultValue undefined (no restriction)
	 */
	scopes?: string[];

	/**
	 * Additional scopes merged with `scopes`.
	 *
	 * @remarks
	 * Combined with `scopes` (deduplicated and sorted) to form the
	 * full `scope-enum` allowlist. Can be used alone or with `scopes`.
	 */
	additionalScopes?: string[];

	/**
	 * Release commit format.
	 *
	 * @remarks
	 * - `"semver"`: `release: v1.2.3`
	 * - `"packages"`: `release: version packages`
	 * - `"scoped"`: `release(pkg): v1.2.3`
	 *
	 * @defaultValue Auto-detected from versioning strategy
	 */
	releaseFormat?: ReleaseFormat;

	/**
	 * Enable emojis in prompt configuration.
	 *
	 * @defaultValue false
	 */
	emojis?: boolean;

	/**
	 * Maximum body line length.
	 *
	 * @remarks
	 * Set higher than the conventional 100 to accommodate detailed
	 * commit messages, especially those generated by AI tools.
	 *
	 * @defaultValue 300
	 */
	bodyMaxLineLength?: number;

	/**
	 * Reject markdown formatting in commit messages.
	 *
	 * @remarks
	 * When enabled, commit messages containing markdown formatting
	 * will be rejected. This includes:
	 * - Headers (`#`, `##`, etc.)
	 * - Numbered lists (`1.`, `2.`)
	 * - Code fences (triple backticks)
	 * - Links (`[text](url)`)
	 * - Bold/italic formatting
	 *
	 * Simple unordered lists (`-` or `*`) are allowed for readability.
	 *
	 * This helps ensure commit messages are plain text and readable
	 * in terminals and tools that don't render markdown. Particularly
	 * useful for preventing overly-formatted AI-generated commits.
	 *
	 * @defaultValue true
	 */
	noMarkdown?: boolean;

	/**
	 * Working directory for auto-detection.
	 *
	 * @remarks
	 * Used as the starting point for detecting DCO files, workspace
	 * packages, and versioning strategy.
	 *
	 * @defaultValue process.cwd()
	 */
	cwd?: string;
}

/**
 * Resolved configuration options after schema decoding applies defaults.
 *
 * @remarks
 * This type represents the options after schema validation, where
 * all defaulted fields are guaranteed to have values.
 *
 * @internal
 */
export type ResolvedConfigOptions = Schema.Schema.Type<typeof ConfigOptionsSchema>;
