/**
 * Behavioral suite for the managed PR body — migrated from
 * `silk-release-action/__test__/pr-body.test.ts` per savvy-web/systems#419
 * ("that evidence should move with the implementation rather than be
 * rediscovered", silk-release-action#209).
 *
 * The behaviour that matters is narrow and easy to lose: **GitHub links an
 * issue when the PR body carries a bare `Closes #N` line outside any fenced
 * block.** Everything else in the body is presentation.
 *
 * Verified against the live repository before the original suite was written:
 * `savvy-web/silk-integration` #242 and #232 were created with an empty body
 * and reported `closingIssuesReferences: []`; #243 carried a bare `Closes #168`
 * and reported `[168]`.
 */

import { describe, expect, it } from "vitest";
import { ManagedPrBody } from "../../src/pr-body/body.js";
import type { LinkedIssueRef } from "../../src/pr-body/linked-issue.js";
import { Markers } from "../../src/pr-body/markers.js";
import { ClosingReferences } from "../../src/pr-body/references.js";

const SIGNOFF = "Signed-off-by: C. Spencer Beggs <spencer@savvyweb.systems>";

const openIssue = (number: number, title = "Some title"): LinkedIssueRef => ({ number, title, state: "open" });
const closedIssue = (number: number, title = "Done already"): LinkedIssueRef => ({ number, title, state: "closed" });

const body = (linkedIssues: ReadonlyArray<LinkedIssueRef>): string =>
	ManagedPrBody.build({
		subject: "release: 2.0.0",
		linkedIssues,
		signoff: SIGNOFF,
		summary: "",
	});

/**
 * Strip every fenced code block.
 *
 * This is the whole point of the suite: a `Closes #N` INSIDE a fence is inert
 * to GitHub's linker. Asserting on the raw body would pass on the
 * proposed-squash-commit block alone and prove nothing.
 */
const outsideFences = (markdown: string): string => markdown.replace(/```[\s\S]*?```/g, "");

describe("ManagedPrBody.build — what it deliberately omits", () => {
	it("carries no boilerplate preamble", () => {
		const rendered = body([openIssue(168)]);

		// The title, branch and author already say this.
		expect(rendered).not.toContain("Release PR");
		expect(rendered).not.toContain("automatically generated by the release workflow");
	});

	it("carries no file-level version listing", () => {
		const rendered = body([openIssue(168)]);
		expect(rendered).not.toContain("Version Changes");
		expect(rendered).not.toContain("pkgs/dependency/package.json");
	});

	it("has no run attribution and no human-readable issue list", () => {
		expect(body([openIssue(170)])).not.toContain("Generated with");
		expect(body([openIssue(170)])).not.toContain("Linked Issues");
	});
});

describe("ManagedPrBody.build — the linking contract", () => {
	it("emits a bare `Closes #N` line OUTSIDE any fenced block", () => {
		const plain = outsideFences(body([openIssue(168)]));
		expect(plain.split("\n").map((l) => l.trim())).toContain("Closes #168");
	});

	it("emits one bare closing line per open issue", () => {
		const plain = outsideFences(body([openIssue(1), openIssue(2), openIssue(3)]));
		const lines = plain.split("\n").map((l) => l.trim());
		expect(lines).toContain("Closes #1");
		expect(lines).toContain("Closes #2");
		expect(lines).toContain("Closes #3");
	});

	it("does NOT emit a closing reference for an already-closed issue", () => {
		const plain = outsideFences(body([openIssue(10), closedIssue(11)]));
		const lines = plain.split("\n").map((l) => l.trim());
		expect(lines).toContain("Closes #10");
		expect(lines).not.toContain("Closes #11");
		// And nowhere else either: a closed issue leaves no trace.
		expect(body([openIssue(10), closedIssue(11)])).not.toContain("#11");
	});

	it("treats GraphQL's uppercase CLOSED as closed too", () => {
		// Ruled in #419: closedness goes through LinkedIssueRef.isClosed, which
		// lowercases — a bare `state !== "closed"` comparison would re-link (and
		// on merge auto-close) an issue a GraphQL payload reported CLOSED.
		const graphqlClosed: LinkedIssueRef = { number: 11, title: "Done", state: "CLOSED" };
		expect(body([openIssue(10), graphqlClosed])).not.toContain("#11");
	});

	it("produces no closing references when nothing is linked", () => {
		expect(outsideFences(body([]))).not.toContain("Closes #");
	});
});

describe("ManagedPrBody.build — the proposed squash-commit block", () => {
	it("fences the block with the `proposed-squash-commit` language", () => {
		expect(body([openIssue(168)])).toContain("```proposed-squash-commit");
		// Pinned as a constant so a well-meaning "fix" to `text` fails here.
		expect(Markers.SQUASH_FENCE_LANGUAGE).toBe("proposed-squash-commit");
	});

	it("carries the subject, the closing reference and the resolved signoff", () => {
		const fenced = /```proposed-squash-commit\n([\s\S]*?)```/.exec(body([openIssue(168)]))?.[1] ?? "";
		expect(fenced).toContain("release: 2.0.0");
		expect(fenced).toContain("Closes #168");
		expect(fenced).toContain(SIGNOFF);
	});

	it("takes the signoff from its argument rather than hard-coding an identity", () => {
		const other = ManagedPrBody.build({
			subject: "release: 1.0.0",
			linkedIssues: [openIssue(5)],
			signoff: "Signed-off-by: Someone Else <other@example.com>",
			summary: "",
		});
		expect(other).toContain("Signed-off-by: Someone Else <other@example.com>");
		expect(other).not.toContain("savvyweb.systems");
	});
});

describe("ManagedPrBody.upsert", () => {
	it("preserves human content written above the managed region", () => {
		const human = "Some notes I typed by hand.\n\nAnd a second paragraph.";
		const first = ManagedPrBody.upsert(human, body([openIssue(168)]));
		expect(first).toContain("Some notes I typed by hand.");
		expect(first).toContain("And a second paragraph.");
		expect(first).toContain(Markers.MANAGED_START);
	});

	it("replaces a previous managed region rather than appending a second one", () => {
		const first = ManagedPrBody.upsert("", body([openIssue(168)]));
		const second = ManagedPrBody.upsert(first, body([openIssue(200)]));

		expect(second.split(Markers.MANAGED_START)).toHaveLength(2);
		expect(second.split(Markers.MANAGED_END)).toHaveLength(2);
		const plain = outsideFences(second)
			.split("\n")
			.map((l) => l.trim());
		expect(plain).toContain("Closes #200");
		expect(plain).not.toContain("Closes #168");
	});

	it("is idempotent: re-upserting the same managed region changes nothing", () => {
		const managed = body([openIssue(168)]);
		const once = ManagedPrBody.upsert("Human note.", managed);
		expect(ManagedPrBody.upsert(once, managed)).toBe(once);
	});

	it("keeps human content when the region is regenerated", () => {
		const human = "Reviewer note: hold until Friday.";
		const first = ManagedPrBody.upsert(human, body([openIssue(168)]));
		const second = ManagedPrBody.upsert(first, body([openIssue(168), openIssue(169)]));
		expect(second).toContain("Reviewer note: hold until Friday.");
		expect(
			outsideFences(second)
				.split("\n")
				.map((l) => l.trim()),
		).toContain("Closes #169");
	});

	it("seeds an empty body with just the managed region", () => {
		const seeded = ManagedPrBody.upsert("", body([openIssue(168)]));
		expect(seeded.startsWith(Markers.MANAGED_START)).toBe(true);
		expect(seeded.trimEnd().endsWith(Markers.MANAGED_END)).toBe(true);
	});
});

describe("the two Closes spellings", () => {
	it("comma-joins inside the squash block and one-per-line outside it", () => {
		const rendered = body([openIssue(170), openIssue(171)]);
		const fenced = /```proposed-squash-commit\n([\s\S]*?)```/.exec(rendered)?.[1] ?? "";
		const plain = outsideFences(rendered)
			.split("\n")
			.map((l) => l.trim());

		// commitlint reads one comma-joined trailer…
		expect(fenced).toContain("Closes #170, #171");
		expect(fenced).not.toContain("Closes #170\nCloses #171");
		// …GitHub's linker reads one bare reference per line. Neither accepts the
		// other's spelling, which is why both are emitted.
		expect(plain).toContain("Closes #170");
		expect(plain).toContain("Closes #171");
		expect(plain).not.toContain("Closes #170, #171");
	});

	it("emits no squash trailer when nothing is linked", () => {
		expect(ClosingReferences.fromIssues([]).renderTrailer()).toBe("");
	});

	it("omits a closed issue from the comma-joined form too", () => {
		expect(ClosingReferences.fromIssues([openIssue(1), closedIssue(2)]).renderTrailer()).toBe("Closes #1");
	});
});

describe("the AI summary region", () => {
	it("reserves the region even when empty, and puts it first", () => {
		const rendered = body([openIssue(170)]);

		expect(rendered).toContain(Markers.SUMMARY_START);
		expect(rendered).toContain(Markers.SUMMARY_END);
		// Nothing of ours may sit above it — a reader meets the prose first.
		expect(rendered.indexOf(Markers.SUMMARY_START)).toBeLessThan(rendered.indexOf("proposed-squash-commit"));
	});

	it("carries an existing summary through a regeneration", () => {
		// The destructive case: the managed region is rebuilt on every run, so a
		// summariser's work must survive the next release commit.
		const withSummary = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(170)],
			signoff: SIGNOFF,
			summary: "This release fixes the widget.",
		});

		expect(ManagedPrBody.extractSummary(withSummary)).toBe("This release fixes the widget.");
		expect(withSummary).toContain("This release fixes the widget.");
	});

	it("reads back nothing from a body that has no region", () => {
		expect(ManagedPrBody.extractSummary("just some prose")).toBe("");
	});

	it("reads back nothing from an empty region", () => {
		expect(ManagedPrBody.extractSummary(body([openIssue(170)]))).toBe("");
	});
});

describe("the closing-reference region", () => {
	it("delimits the bare references with markers, keeping them outside the fence", () => {
		const rendered = body([openIssue(168)]);

		// The generator emits the attributed opening form, not the plain constant.
		expect(rendered).toContain(Markers.REFERENCES_START_PREFIX);
		expect(rendered).toContain(Markers.REFERENCES_END);
		// The markers must not push the references inside a fence — that would
		// make them inert to GitHub's linker, which is the whole point of them.
		expect(
			outsideFences(rendered)
				.split("\n")
				.map((l) => l.trim()),
		).toContain("Closes #168");
	});

	it("reserves the region even when nothing is linked", () => {
		// An empty region is still an addressable one. A release with nothing
		// linked is exactly when an agent most wants somewhere to write.
		const rendered = body([]);
		expect(rendered).toContain(Markers.REFERENCES_START_PREFIX);
		expect(rendered).toContain(Markers.REFERENCES_END);
		expect(ManagedPrBody.extractReferences(rendered)).toBe("");
	});

	it("reads back its own references", () => {
		expect(ManagedPrBody.extractReferences(body([openIssue(1), openIssue(2)]))).toBe("Closes #1\nCloses #2");
	});

	it("reads back nothing from a body that has no region", () => {
		expect(ManagedPrBody.extractReferences("just some prose")).toBe("");
	});

	it("carries through a reference for an issue this run does not know about", () => {
		// The destructive case the markers exist to prevent: an agent links an
		// issue the release never detected, and the next push rebuilds the region
		// from `linkedIssues` alone and deletes it silently.
		const withAgentEdit = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(170)],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${Markers.REFERENCES_START}\nCloses #999\n${Markers.REFERENCES_END}`,
		});

		const plain = outsideFences(withAgentEdit)
			.split("\n")
			.map((l) => l.trim());
		expect(plain).toContain("Closes #170");
		expect(plain).toContain("Closes #999");
	});

	it("does not resurrect an issue this run deliberately dropped as closed", () => {
		// The generator decides every issue it knows about. A stale carried line
		// must not re-link an issue that has since been closed.
		const rendered = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(10), closedIssue(11)],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `<!-- silk-release:references:start owned="10,11" -->\nCloses #10\nCloses #11\n${Markers.REFERENCES_END}`,
		});

		expect(rendered).not.toContain("#11");
	});

	it("does not duplicate a carried reference it already emits", () => {
		const rendered = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(170)],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${Markers.REFERENCES_START}\nCloses #170\nCloses #170\n${Markers.REFERENCES_END}`,
		});

		// Scoped to the region: the squash block legitimately carries its own
		// copy, so counting across the whole body proves nothing.
		expect(ManagedPrBody.extractReferences(rendered).match(/Closes #170/g)).toHaveLength(1);
	});

	it("ignores a number that no closing keyword governs", () => {
		const rendered = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${Markers.REFERENCES_START}\nSee also #500\nRelated to #501\n${Markers.REFERENCES_END}`,
		});

		expect(rendered).not.toContain("#500");
		expect(rendered).not.toContain("#501");
	});

	it("recognises every closing keyword GitHub accepts, not just the one it emits", () => {
		// A keyword this parser fails to match is a reference it deletes on the
		// next run — the exact destruction the region exists to prevent.
		const rendered = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${Markers.REFERENCES_START}\nFixes: #601\nClosed #602\nresolve #603\nFIX #604\n${Markers.REFERENCES_END}`,
		});

		const carried = ManagedPrBody.extractReferences(rendered);
		expect(carried).toContain("Closes #601");
		expect(carried).toContain("Closes #602");
		expect(carried).toContain("Closes #603");
		expect(carried).toContain("Closes #604");
	});

	it("does not let a lookalike attribute claim an agent's reference as its own", () => {
		// An unanchored `owned="…"` match also finds `data-owned="…"`, which would
		// mark #700 as previously-emitted and drop it.
		const rendered = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `<!-- silk-release:references:start data-owned="700" -->\nCloses #700\n${Markers.REFERENCES_END}`,
		});

		expect(ManagedPrBody.extractReferences(rendered)).toContain("Closes #700");
	});

	it("emits one reference per issue when the same issue is linked twice", () => {
		const rendered = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [openIssue(170), openIssue(170)],
			signoff: SIGNOFF,
			summary: "",
		});

		expect(ManagedPrBody.extractReferences(rendered).match(/Closes #170/g)).toHaveLength(1);
		expect(rendered).toContain('owned="170"');
	});

	it("preserves a hostile `Closes #0` carried line instead of failing", () => {
		// Hardening: carried ids flow through ClosingReferences.make, whose ids
		// are deliberately NOT constrained `> 0` — a `Closes #0` line in an
		// untrusted prior body must stay a preserved oddity (the fail-safe
		// direction), never a mid-regeneration construction defect.
		const rendered = ManagedPrBody.build({
			subject: "release: 2.0.0",
			linkedIssues: [],
			signoff: SIGNOFF,
			summary: "",
			priorBody: `${Markers.REFERENCES_START}\nCloses #0\n${Markers.REFERENCES_END}`,
		});

		expect(ManagedPrBody.extractReferences(rendered)).toContain("Closes #0");
	});

	it("survives a full regeneration round-trip through the managed region", () => {
		const first = ManagedPrBody.upsert(
			"",
			ManagedPrBody.build({
				subject: "release: 1.0.0",
				linkedIssues: [openIssue(170)],
				signoff: SIGNOFF,
				summary: "",
				priorBody: `${Markers.REFERENCES_START}\nCloses #999\n${Markers.REFERENCES_END}`,
			}),
		);

		const second = ManagedPrBody.upsert(
			first,
			ManagedPrBody.build({
				subject: "release: 2.0.0",
				linkedIssues: [openIssue(171)],
				signoff: SIGNOFF,
				summary: ManagedPrBody.extractSummary(first),
				priorBody: first,
			}),
		);

		const plain = outsideFences(second)
			.split("\n")
			.map((l) => l.trim());
		// This run's own reference, and the agent's addition still standing.
		expect(plain).toContain("Closes #171");
		expect(plain).toContain("Closes #999");
		// #170 belonged to the previous run and is no longer linked.
		expect(plain).not.toContain("Closes #170");
	});

	it("an agent-added reference survives repeated regenerations", () => {
		// Property stated as a sentence: a carried reference not in `owned` and
		// not in the linked set survives N regenerations unchanged.
		let current = ManagedPrBody.upsert(
			"",
			ManagedPrBody.build({
				subject: "release: 1.0.0",
				linkedIssues: [openIssue(1)],
				signoff: SIGNOFF,
				summary: "",
				priorBody: `${Markers.REFERENCES_START}\nCloses #4242\n${Markers.REFERENCES_END}`,
			}),
		);
		for (let run = 0; run < 5; run += 1) {
			current = ManagedPrBody.upsert(
				current,
				ManagedPrBody.build({
					subject: `release: 1.0.${run + 1}`,
					linkedIssues: [openIssue(1)],
					signoff: SIGNOFF,
					summary: ManagedPrBody.extractSummary(current),
					priorBody: current,
				}),
			);
		}
		expect(ManagedPrBody.extractReferences(current)).toContain("Closes #4242");
	});
});
