# Generated by pluginfinity. Do not edit.
_PF_TOOLS='Read=view
Bash=bash
Edit=edit
MultiEdit=edit
Write=create
Agent=task
Task=task
Grep=grep
Glob=glob
WebFetch=web_fetch
WebSearch=web_search
Skill=skill'
_PF_TOOLS_PLUGIN='silk'
_PF_TOOLS_MCP='{server}-{tool}'
_PF_TOOLS_SERVERS='savvy-mcp'
_PF_TOOLS_UNLISTED=unresolved
_PF_HAS_SKILLS='build changeset changeset-config changeset-style commit-create config delete dependencies dogfood merge pr-body repos status tsdoc turbo update'
_PF_HAS_AGENTS='changeset-manager tsdoctor turborepo'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS='savvy-mcp'
