import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "@effect/vitest";
import { Effect } from "effect";

import { runValidateFile } from "../../src/commands/changeset/commands/validate-file.js";
import { Capture } from "../utils/capture.js";
import { TestExit } from "../utils/exit.js";

/** What the last run wrote to stderr: every log line. */
const stderrLines: string[] = [];

describe("runValidateFile", () => {
	let tempDir: string;

	beforeEach(() => {
		tempDir = mkdtempSync(join(tmpdir(), "cli-validate-file-"));
		TestExit.reset();
	});

	afterEach(() => {
		rmSync(tempDir, { recursive: true });
	});

	function collectLogs(filePath: string) {
		return Effect.gen(function* () {
			// stdout only: the findings (and the verdict) are the command's output.
			const logs: string[] = [];
			stderrLines.length = 0;
			yield* runValidateFile(filePath).pipe(Effect.provide(Capture.layer(logs, stderrLines)));
			return logs;
		}).pipe(Effect.provide(TestExit.layer));
	}

	it.effect("exits cleanly for a valid changeset file", () =>
		Effect.gen(function* () {
			const filePath = join(tempDir, "good.md");
			writeFileSync(filePath, '---\n"@savvy-web/changesets": minor\n---\n\n## Features\n\n- Added CLI\n');

			const logs = yield* collectLogs(filePath);

			expect(TestExit.code()).toBe(0);
			expect(logs).toEqual(["✓ Valid"]);
		}),
	);

	it.effect("sets the exit code=1 and logs errors for invalid file", () =>
		Effect.gen(function* () {
			const filePath = join(tempDir, "bad.md");
			writeFileSync(filePath, '---\n"@savvy-web/changesets": minor\n---\n\n# Bad Title\n');

			const logs = yield* collectLogs(filePath);

			expect(TestExit.code()).toBe(1);
			// One report, one unwrapped `file:line:col rule message` line per error.
			expect(logs).toHaveLength(1);
			const lines = logs[0].split("\n");
			expect(lines.length).toBeGreaterThan(0);
			for (const line of lines) {
				expect(line.startsWith(`${filePath}:`)).toBe(true);
				expect(line.slice(filePath.length)).toMatch(/^:\d+:\d+ \S+ .+$/);
			}
		}),
	);

	it.effect("prints each finding as an exact `file:line:col rule message` line (hooks parse it)", () =>
		Effect.gen(function* () {
			const filePath = join(tempDir, "bad.md");
			writeFileSync(filePath, '---\n"@savvy-web/changesets": minor\n---\n\n# Bad Title\n');

			const logs = yield* collectLogs(filePath);

			expect(logs).toEqual([`${filePath}:2:1 changeset-heading-hierarchy ${H1_MESSAGE}`]);
		}),
	);

	it.effect("prints the same unwrapped lines for an agent and under GitHub Actions", () =>
		Effect.gen(function* () {
			const filePath = join(tempDir, "bad.md");
			writeFileSync(filePath, '---\n"@savvy-web/changesets": minor\n---\n\n# Bad Title\n');
			const expected = [`${filePath}:2:1 changeset-heading-hierarchy ${H1_MESSAGE}`];

			const agent = yield* Capture.run(runValidateFile(filePath), { audience: "agent" });
			const actions = yield* Capture.run(runValidateFile(filePath), { audience: "ci", githubActions: true });

			expect(agent.stdout).toEqual(expected);
			expect(actions.stdout).toEqual(expected);
		}),
	);

	it.effect("fails with a CommandError, reported on stderr with exit 1, when the file does not exist", () =>
		Effect.gen(function* () {
			const filePath = join(tempDir, "nonexistent.md");

			const result = yield* Capture.main(runValidateFile(filePath));

			expect(result.exitCode).toBe(1);
			expect(result.stdout).toEqual([]);
			expect(result.stderr.join("\n").replace(/\s+/g, " ")).toContain(`✗ could not validate ${filePath} ENOENT`);
		}),
	);
});

/** The CSH001 message the linter attaches to an h1. */
const H1_MESSAGE =
	'h1 headings are not allowed in changeset files. Use h2 (##) for top-level sections like "## Features" or "## Bug Fixes". h1 is reserved for the version title generated by the changelog formatter. See: https://github.com/savvy-web/systems/blob/main/packages/silk-effects/docs/rules/CSH001.md';
