# Generated by pluginfinity. Do not edit.
_PF_TOOLS=''
_PF_TOOLS_PLUGIN='silk'
_PF_TOOLS_MCP='mcp__plugin_{plugin}_{server}__{tool}'
_PF_TOOLS_SERVERS='savvy-mcp'
_PF_TOOLS_UNLISTED=keep
_PF_HAS_SKILLS='build changeset changeset-config changeset-style commit-create config delete dependencies dogfood it2 merge pr-body repos status tsdoc turbo update'
_PF_HAS_AGENTS='changeset-manager tsdoctor turborepo'
_PF_HAS_MONITORS='tsdoc-diagnostics dogfood-mail gitmodules-drift'
_PF_HAS_SERVERS='savvy-mcp'
