/**
 * Generate `source: generated` API-reference markdown into the resource corpus
 * from each target package's API Extractor model. Ephemeral: output lands under
 * content/packages/<dir>/api/** (gitignored) and is recompiled into the manifest
 * by build:catalog. Missing models are skipped with a warning so a bare install
 * (which runs `prepare: turbo run build:dev`) never fails.
 *
 * @internal
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ApiItemRef, DocMeta } from "api-extractor-llms";
import { loadApiModel, renderPackage } from "api-extractor-llms";
import type { ApiTarget } from "./api-targets.js";
import { API_TARGETS } from "./api-targets.js";

const here = dirname(fileURLToPath(import.meta.url));
// API Extractor models are pre-generated by the build system into the local
// lib/models/<dir>/ folder, so this script reads from there instead of reaching
// into each sibling package's dist/ — keeping the task's inputs inside this
// package so turbo can cache it.
const modelsRoot = join(here, "..", "models"); // packages/mcp/lib/scripts -> packages/mcp/lib/models
const contentRoot = join(here, "..", "..", "public", "content"); // -> packages/mcp/public/content

export interface GeneratedFrontMatter {
	readonly id: string;
	readonly title: string;
	readonly summary: string;
	readonly tier: "packages";
	readonly source: "generated";
	readonly tags: ReadonlyArray<string>;
	readonly priority: number;
	readonly related: ReadonlyArray<string>;
}

const truncate = (s: string, max = 160): string => (s.length <= max ? s : `${s.slice(0, max - 1).trimEnd()}…`);

/** Pure: derive the structured front-matter for one rendered item's metadata. */
export function frontMatterFor(
	target: ApiTarget,
	meta: Pick<DocMeta, "name" | "kind" | "slug" | "summary">,
): GeneratedFrontMatter {
	const summary = meta.summary.trim() || `${meta.kind} ${meta.name} from ${target.packageName}.`;
	return {
		id: `${target.idPrefix}/api/${meta.kind}/${meta.slug}`,
		title: `${meta.name} — ${target.dir} ${meta.kind}`,
		summary: truncate(summary),
		tier: "packages",
		source: "generated",
		tags: [target.dir, "api"],
		priority: 0.3,
		related: [],
	};
}

/**
 * Front-matter for a package's API index page, served at the bare
 * `silk://<idPrefix>/api` URI. Names the package in the title so a
 * package-level query (e.g. "bundler") matches it, and ranks above the
 * per-symbol pages.
 */
export function indexFrontMatterFor(target: ApiTarget, symbolCount: number): GeneratedFrontMatter {
	return {
		id: `${target.idPrefix}/api`,
		title: `${target.packageName} — API reference`,
		summary: truncate(`${target.packageName} API reference: ${symbolCount} documented symbols.`),
		tier: "packages",
		source: "generated",
		tags: [target.dir, "api"],
		priority: 0.4,
		related: [],
	};
}

/** A symbol shown on a package's API index page. */
export interface ApiIndexItem {
	readonly name: string;
	readonly kind: string;
	readonly slug: string;
	readonly summary: string;
}

/** Render the index body: symbols grouped by kind, each linking to its silk:// page. */
export function renderApiIndexBody(target: ApiTarget, items: ReadonlyArray<ApiIndexItem>): string {
	const byKind = new Map<string, ApiIndexItem[]>();
	for (const item of items) {
		const bucket = byKind.get(item.kind) ?? [];
		bucket.push(item);
		byKind.set(item.kind, bucket);
	}
	const lines: string[] = [`# ${target.packageName} — API reference`, ""];
	for (const kind of [...byKind.keys()].sort()) {
		lines.push(`## ${kind}`, "");
		for (const item of (byKind.get(kind) ?? []).slice().sort((a, b) => a.name.localeCompare(b.name))) {
			const uri = `silk://${target.idPrefix}/api/${item.kind}/${item.slug}`;
			const summary = item.summary.trim();
			lines.push(`- [\`${item.name}\`](${uri})${summary ? ` — ${summary}` : ""}`);
		}
		lines.push("");
	}
	return `${lines.join("\n").trimEnd()}\n`;
}

/** Serialize the structured front-matter to a YAML block (incl. trailing blank line). */
const toYaml = (fm: GeneratedFrontMatter): string =>
	[
		"---",
		`id: ${fm.id}`,
		`title: ${JSON.stringify(fm.title)}`,
		`summary: ${JSON.stringify(fm.summary)}`,
		`tier: ${fm.tier}`,
		`source: ${fm.source}`,
		`tags: [${fm.tags.join(", ")}]`,
		`priority: ${fm.priority}`,
		"related: []",
		"---",
		"",
		"",
	].join("\n");

/** The mcp crosslink scheme: silk:// URIs within this target's api namespace. */
const routeForTarget =
	(target: ApiTarget) =>
	(ref: ApiItemRef): string =>
		`silk://${target.idPrefix}/api/${ref.kind}/${ref.slug}`;

/** Resolve a target's pre-generated model under lib/models/<dir>/<modelBasename>. */
function findModel(target: ApiTarget): string | undefined {
	const candidate = join(modelsRoot, target.dir, target.modelBasename);
	return existsSync(candidate) ? candidate : undefined;
}

async function generateTarget(target: ApiTarget): Promise<number> {
	const modelPath = findModel(target);
	const outDir = join(contentRoot, "packages", target.dir, "api");
	// Always clear stale output so a removed export does not leave an orphan doc.
	if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
	if (modelPath === undefined) {
		process.stderr.write(
			`[generate-api-docs] SKIP ${target.packageName}: no model under lib/models (build it first)\n`,
		);
		return 0;
	}
	const pkg = await loadApiModel(modelPath);
	// Inject the two consumer-specific services; the shared system returns docs
	// whose markdown already includes the silk front-matter and silk:// crosslinks.
	const docs = renderPackage(pkg, {
		packageName: target.packageName,
		routeFor: routeForTarget(target),
		frontmatter: (meta) => toYaml(frontMatterFor(target, meta)),
	});
	for (const doc of docs) {
		const fileDir = join(outDir, doc.kind);
		mkdirSync(fileDir, { recursive: true });
		writeFileSync(join(fileDir, `${doc.slug}.md`), doc.markdown);
	}
	// Index page served at the bare `silk://<idPrefix>/api` URI (#179). Lives next
	// to the api/ dir as api.md so paths.ts resolves the bare path to it, and gives
	// search a package-level entry point that names the package. The loop above
	// already created `packages/<dir>/` via the per-kind mkdir.
	const indexBody = renderApiIndexBody(target, docs);
	writeFileSync(`${outDir}.md`, toYaml(indexFrontMatterFor(target, docs.length)) + indexBody);
	process.stderr.write(`[generate-api-docs] ${target.packageName}: ${docs.length} docs\n`);
	return docs.length;
}

async function main(): Promise<void> {
	let total = 0;
	for (const target of API_TARGETS) total += await generateTarget(target);
	process.stderr.write(`[generate-api-docs] wrote ${total} generated docs\n`);
}

// Only run as a script, not when imported by tests.
if (basename(process.argv[1] ?? "") === "generate-api-docs.ts") {
	main().catch((err) => {
		process.stderr.write(`generate-api-docs: ${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`);
		process.exit(1);
	});
}
