/**
 * Tagged errors for \@savvy-web/changesets.
 *
 * @remarks
 * All errors in this module extend Effect's `Data.TaggedError`, enabling
 * type-safe error handling via `Effect.catchTag`. Each error class carries
 * structured metadata (not just a string message) so that callers can
 * programmatically inspect failure details.
 *
 * The `*Base` exports are anonymous base classes generated by
 * `Data.TaggedError()`. They are exported solely for api-extractor
 * compatibility and should not be used directly.
 *
 * @see {@link https://effect.website/docs/data-types/data#taggerror | Effect TaggedError documentation}
 *
 * @packageDocumentation
 */

import { Data } from "effect";

/**
 * Base class for {@link ChangesetValidationError}.
 *
 * @privateRemarks
 * This export is required for api-extractor documentation generation.
 * Effect's Data.TaggedError creates an anonymous base class that must be
 * explicitly exported to avoid "forgotten export" warnings. Do not delete.
 *
 * @internal
 */
export const ChangesetValidationErrorBase = Data.TaggedError("ChangesetValidationError");

/**
 * Changeset file validation failure.
 *
 * @remarks
 * Raised when a changeset markdown file fails structural validation
 * (e.g., missing summary, invalid heading, malformed dependency table).
 * Carries an array of structured issues, each with a JSON-path pointing
 * to the problematic field and a human-readable message.
 *
 * @example
 * ```typescript
 * import { Effect } from "effect";
 * import { ChangesetValidationError } from "@savvy-web/changesets";
 *
 * declare const program: Effect.Effect<void, ChangesetValidationError>;
 *
 * const handled = program.pipe(
 * 	Effect.catchTag("ChangesetValidationError", (err) => {
 * 		for (const issue of err.issues) {
 * 			console.error(`${issue.path}: ${issue.message}`);
 * 		}
 * 		return Effect.void;
 * 	}),
 * );
 * ```
 *
 * @see {@link ChangesetSchema} for the schema that drives validation
 *
 * @public
 */
export class ChangesetValidationError extends ChangesetValidationErrorBase<{
	/** File path of the changeset that failed validation. */
	readonly file?: string | undefined;
	/** Individual validation issues found. */
	readonly issues: ReadonlyArray<{
		/** JSON-path to the problematic field. */
		readonly path: string;
		/** Human-readable description of the issue. */
		readonly message: string;
	}>;
}> {
	get message() {
		const prefix = this.file ? `${this.file}: ` : "";
		const detail = this.issues.map((i) => `  - ${i.path}: ${i.message}`).join("\n");
		return `${prefix}Changeset validation failed:\n${detail}`;
	}
}

/**
 * Base class for {@link GitHubApiError}.
 *
 * @privateRemarks
 * This export is required for api-extractor documentation generation.
 * Effect's Data.TaggedError creates an anonymous base class that must be
 * explicitly exported to avoid "forgotten export" warnings. Do not delete.
 *
 * @internal
 */
export const GitHubApiErrorBase = Data.TaggedError("GitHubApiError");

/**
 * GitHub API request failure.
 *
 * @remarks
 * Raised when a call to the GitHub API (via `\@changesets/get-github-info`)
 * fails due to network issues, authentication errors, rate limiting, or
 * server errors. Use the {@link GitHubApiError.isRetryable | isRetryable}
 * property to determine whether a retry strategy should be applied.
 * Rate-limited responses (403/429) and server errors (5xx) are considered
 * retryable.
 *
 * @example
 * ```typescript
 * import { Effect, Schedule } from "effect";
 * import { GitHubApiError } from "@savvy-web/changesets";
 *
 * declare const program: Effect.Effect<void, GitHubApiError>;
 *
 * const withRetry = program.pipe(
 * 	Effect.catchTag("GitHubApiError", (err) => {
 * 		if (err.isRetryable) {
 * 			return Effect.retry(program, Schedule.exponential("1 second"));
 * 		}
 * 		return Effect.fail(err);
 * 	}),
 * );
 * ```
 *
 * @see {@link GitHubService} for the Effect service that may produce this error
 *
 * @public
 */
export class GitHubApiError extends GitHubApiErrorBase<{
	/** The API operation that failed (e.g., `"getInfo"`). */
	readonly operation: string;
	/** HTTP status code, if available. */
	readonly statusCode?: number | undefined;
	/** Human-readable failure reason. */
	readonly reason: string;
}> {
	get message() {
		const status = this.statusCode ? ` (${this.statusCode})` : "";
		return `GitHub API error during ${this.operation}${status}: ${this.reason}`;
	}

	/** Whether this error is a rate-limit response (403 or 429). */
	public get isRateLimited(): boolean {
		return this.statusCode === 403 || this.statusCode === 429;
	}

	/** Whether this error is eligible for retry (server errors or rate limits). */
	public get isRetryable(): boolean {
		return this.statusCode !== undefined && (this.statusCode >= 500 || this.isRateLimited);
	}
}

/**
 * Base class for {@link MarkdownParseError}.
 *
 * @privateRemarks
 * This export is required for api-extractor documentation generation.
 * Effect's Data.TaggedError creates an anonymous base class that must be
 * explicitly exported to avoid "forgotten export" warnings. Do not delete.
 *
 * @internal
 */
export const MarkdownParseErrorBase = Data.TaggedError("MarkdownParseError");

/**
 * Markdown parsing failure.
 *
 * @remarks
 * Raised when a markdown file cannot be parsed into an AST by the unified/remark
 * pipeline. Carries optional source file location information (line, column)
 * for diagnostic display.
 *
 * @example
 * ```typescript
 * import { Effect } from "effect";
 * import { MarkdownParseError } from "@savvy-web/changesets";
 *
 * declare const program: Effect.Effect<string, MarkdownParseError>;
 *
 * const handled = program.pipe(
 * 	Effect.catchTag("MarkdownParseError", (err) => {
 * 		console.error(err.message);
 * 		return Effect.succeed("");
 * 	}),
 * );
 * ```
 *
 * @see {@link MarkdownService} for the Effect service that may produce this error
 *
 * @public
 */
export class MarkdownParseError extends MarkdownParseErrorBase<{
	/** Source file path, if known. */
	readonly source?: string | undefined;
	/** Human-readable failure reason. */
	readonly reason: string;
	/** Line number where the error occurred (1-based). */
	readonly line?: number | undefined;
	/** Column number where the error occurred (1-based). */
	readonly column?: number | undefined;
}> {
	get message() {
		const loc = this.line ? `:${this.line}${this.column ? `:${this.column}` : ""}` : "";
		const src = this.source ? `${this.source}${loc}: ` : "";
		return `${src}Markdown parse error: ${this.reason}`;
	}
}

/**
 * Base class for {@link ConfigurationError}.
 *
 * @privateRemarks
 * This export is required for api-extractor documentation generation.
 * Effect's Data.TaggedError creates an anonymous base class that must be
 * explicitly exported to avoid "forgotten export" warnings. Do not delete.
 *
 * @internal
 */
export const ConfigurationErrorBase = Data.TaggedError("ConfigurationError");

/**
 * Invalid or missing configuration.
 *
 * @remarks
 * Raised when the changeset configuration (typically from `.changeset/config.json`)
 * is missing required fields, has invalid values, or cannot be parsed. The `field`
 * property identifies which configuration field is problematic, and `reason`
 * provides an actionable message.
 *
 * @example
 * ```typescript
 * import { Effect } from "effect";
 * import { ConfigurationError, validateChangesetOptions } from "@savvy-web/changesets";
 *
 * const program = validateChangesetOptions({ repo: "invalid" }).pipe(
 * 	Effect.catchTag("ConfigurationError", (err) => {
 * 		console.error(`Field "${err.field}": ${err.reason}`);
 * 		return Effect.fail(err);
 * 	}),
 * );
 * ```
 *
 * @see {@link ChangesetOptionsSchema} for the expected configuration shape
 * @see {@link validateChangesetOptions} for the validation function that produces this error
 *
 * @public
 */
export class ConfigurationError extends ConfigurationErrorBase<{
	/** Configuration field that is invalid or missing. */
	readonly field: string;
	/** Human-readable failure reason. */
	readonly reason: string;
}> {
	get message() {
		return `Configuration error (${this.field}): ${this.reason}`;
	}
}

/**
 * Base class for {@link VersionFileError}.
 *
 * @privateRemarks
 * This export is required for api-extractor documentation generation.
 * Effect's Data.TaggedError creates an anonymous base class that must be
 * explicitly exported to avoid "forgotten export" warnings. Do not delete.
 *
 * @internal
 */
export const VersionFileErrorBase = Data.TaggedError("VersionFileError");

/**
 * Version file update failure.
 *
 * @remarks
 * Raised when a JSON file targeted by the `versionFiles` configuration option
 * cannot be read, parsed, or updated at the specified JSONPath. Common causes
 * include missing files, invalid JSON, or JSONPath expressions that do not
 * match any field in the target file.
 *
 * @example
 * ```typescript
 * import { Effect } from "effect";
 * import { VersionFileError } from "@savvy-web/changesets";
 *
 * declare const program: Effect.Effect<void, VersionFileError>;
 *
 * const handled = program.pipe(
 * 	Effect.catchTag("VersionFileError", (err) => {
 * 		console.error(`Failed to update ${err.filePath}: ${err.reason}`);
 * 		if (err.jsonPath) {
 * 			console.error(`  at JSONPath: ${err.jsonPath}`);
 * 		}
 * 		return Effect.void;
 * 	}),
 * );
 * ```
 *
 * @see {@link VersionFilesSchema} for the configuration that drives version file updates
 * @see {@link JsonPathSchema} for JSONPath expression validation
 *
 * @public
 */
export class VersionFileError extends VersionFileErrorBase<{
	/** Absolute path to the file that failed. */
	readonly filePath: string;
	/** JSONPath expression that failed, if applicable. */
	readonly jsonPath?: string | undefined;
	/** Human-readable failure reason. */
	readonly reason: string;
}> {
	get message() {
		const path = this.jsonPath ? ` at ${this.jsonPath}` : "";
		return `Version file error (${this.filePath}${path}): ${this.reason}`;
	}
}

/**
 * Base class for {@link GitError}.
 *
 * @privateRemarks
 * Effect's `Data.TaggedError` creates an anonymous base class that
 * api-extractor cannot follow without an explicit export.
 *
 * @internal
 */
export const GitErrorBase = Data.TaggedError("GitError");

/**
 * Git command failure.
 *
 * @remarks
 * Raised by services that shell out to `git` — `BranchAnalyzer` is the
 * canonical consumer. Captures the failing command, the working directory
 * it was invoked in, and the underlying reason (often the captured stderr
 * from the child process) so callers can produce actionable diagnostics.
 *
 * @example
 * ```typescript
 * import { Effect } from "effect";
 * import { GitError } from "@savvy-web/changesets";
 *
 * declare const program: Effect.Effect<void, GitError>;
 *
 * const handled = program.pipe(
 *   Effect.catchTag("GitError", (err) =>
 *     Effect.logError(`git failed in ${err.cwd}: ${err.command}\n${err.reason}`)
 *   ),
 * );
 * ```
 *
 * @see {@link BranchAnalyzer} which produces these errors when computing
 *   merge bases or running `git diff`
 *
 * @public
 */
export class GitError extends GitErrorBase<{
	/** The git command that failed, including arguments. */
	readonly command: string;
	/** Working directory in which the command was invoked. */
	readonly cwd: string;
	/** Human-readable failure reason — typically the captured stderr or thrown error message. */
	readonly reason: string;
}> {
	get message() {
		return `git command failed in ${this.cwd}: ${this.command}\n${this.reason}`;
	}
}
