# split-segments.sh — shared quote-aware, control-operator command segmenter
# and runner-prefix peeler for the Biome command-position hooks
# (pre-tool-use/biome-prefer-mcp.sh, pre-tool-use/biome-direct-deny.sh).
#
# Source from a hook script, AFTER hook-output.sh / hook-debug.sh / hook-env.sh:
#   . "${CLAUDE_PLUGIN_ROOT}/hooks/lib/split-segments.sh"
#
# Both hooks need to find a token in COMMAND POSITION -- the start of the
# whole command, or of a sub-command following a control operator (`;`, `|`,
# `&`, `(`, or a newline) -- while ignoring any mention of that token inside a
# quoted argument (savvy-web/systems#248) and staying fast on multi-KB
# heredoc commands (savvy-web/systems#250: the awk-based O(n) segmenter below
# replaced a quadratic bash char-by-char scan). Extracted here (rather than
# left duplicated) so a future fix to either only has to happen once
# (savvy-web/systems#380 fix round 1).

# hook_split_segments <cmd> -- splits <cmd> into sub-command segments,
# appending each to the global HOOK_CMD_SEGMENTS array. The caller must
# initialize HOOK_CMD_SEGMENTS=() itself before calling: this is a plain
# global array, not a nameref, since each hook always runs as its own
# `bash "$HOOK"` subprocess -- there is no cross-hook collision risk.
#
# RS is set to "\001" (SOH), not "\0": this awk (and several others) treats
# RS="\0" as equivalent to RS="" (paragraph mode) internally, which silently
# strips a leading run of newlines and splits the record on blank lines --
# both would corrupt a multi-line heredoc $cmd. "\001" is a control byte that
# cannot appear in a bash command string typed or generated by the agent, so
# it is safe as a real "read the whole stdin as one record" sentinel.
hook_split_segments() {
	local cmd="$1"
	if [ -z "$cmd" ]; then
		HOOK_CMD_SEGMENTS+=("")
		return 0
	fi
	local _seg
	while IFS= read -r -d '' _seg; do
		HOOK_CMD_SEGMENTS+=("$_seg")
	done < <(
		printf '%s' "$cmd" | awk '
			BEGIN { RS = "\001"; in_s = 0; in_d = 0 }
			{
				n = split($0, arr, "")
				start = 1
				for (i = 1; i <= n; i++) {
					ch = arr[i]
					if (in_s == 0 && in_d == 0) {
						if (ch == "\047") { in_s = 1 }
						else if (ch == "\"") { in_d = 1 }
						else if (ch == ";" || ch == "|" || ch == "&" || ch == "(" || ch == "\n") {
							printf "%s%c", substr($0, start, i - start), 0
							start = i + 1
						}
					} else {
						if (in_s == 1 && ch == "\047") { in_s = 0 }
						if (in_d == 1 && ch == "\"") { in_d = 0 }
					}
				}
				printf "%s%c", substr($0, start), 0
			}
		'
	)
}

# hook_peel_segment_prefix <segment> -- echoes <segment> with leading tokens
# that precede the actual invoked binary stripped off, repeatedly, until none
# remain: env / inline VAR=value / sudo|command|time / exec|npx|bunx / the
# two-token `bun x` alias for bunx / the two-token `pnpm dlx`|`yarn dlx`
# alias for npx / pnpm|npm|yarn|bun (optionally followed by "run"). This
# reduces a segment all the way down to the invoked binary name, so `npx
# biome`, `pnpm dlx biome`, `sudo biome`, `pnpm run biome`, and `exec biome`
# all end up matching a bare `biome` check.
#
# Both biome-prefer-mcp.sh (nudge) and biome-direct-deny.sh (deny) use this
# single peel -- there is no longer a narrower "neutral" mode that leaves
# npx/bunx unpeeled. That mode existed only so the pre-reversal deny hook
# could match the literal tokens `npx`/`bunx` immediately before `biome`,
# which was how it exempted `npx @biomejs/biome` (a different token right
# after npx). The reversal denies the scoped package too, so the deny hook
# no longer needs npx/bunx to survive peeling -- it fully peels to the
# invoked binary like the nudge hook always has, and relies on the bare-biome
# match's optional path-prefix group to catch `@biomejs/biome` the same way
# it already catches `/usr/local/bin/biome` (the leading run of non-space
# characters ending in "/" is not distinguished from a package scope).
#
# `sudo`/`command`/`time` and the `bun x` / `pnpm dlx` / `yarn dlx` aliases
# are ADDITIONS beyond what either hook peeled before: both hooks want the
# wider net, since an agent routing around a "cannot run biome" refusal
# reaches for whichever wrapper or runner alias is available, not only the
# ones a narrower peel happened to already recognize.
hook_peel_segment_prefix() {
	local seg="$1"
	seg="${seg#"${seg%%[![:space:]]*}"}"

	local changed=1
	while [ "$changed" -eq 1 ]; do
		changed=0
		if [[ "$seg" =~ ^env[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[1]}"
			changed=1
			continue
		fi
		if [[ "$seg" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(\"[^\"]*\"|\'[^\']*\'|[^[:space:]]*)[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[3]}"
			changed=1
			continue
		fi
		if [[ "$seg" =~ ^(sudo|command|time)[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[2]}"
			changed=1
			continue
		fi
		if [[ "$seg" =~ ^(exec|npx|bunx)[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[2]}"
			changed=1
			continue
		fi
		# `bun x <pkg>` -- two-token alias for `bunx <pkg>`. Must be checked
		# BEFORE the bare pnpm|npm|yarn|bun peel below, or that branch would
		# strip only "bun" and leave a bogus "x <pkg>" segment (treating the
		# literal "x" as an invoked script name) instead of peeling through
		# to <pkg>.
		if [[ "$seg" =~ ^bun[[:space:]]+x[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[1]}"
			changed=1
			continue
		fi
		# `pnpm dlx <pkg>` / `yarn dlx <pkg>` -- the pnpm/yarn equivalents of
		# `npx <pkg>`. Same ordering requirement as `bun x` above: must
		# precede the bare pnpm|npm|yarn|bun peel.
		if [[ "$seg" =~ ^(pnpm|yarn)[[:space:]]+dlx[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[2]}"
			changed=1
			continue
		fi
		if [[ "$seg" =~ ^(pnpm|npm|yarn|bun)[[:space:]]+run[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[2]}"
			changed=1
			continue
		fi
		if [[ "$seg" =~ ^(pnpm|npm|yarn|bun)[[:space:]]+(.*) ]]; then
			seg="${BASH_REMATCH[2]}"
			changed=1
			continue
		fi
	done

	printf '%s' "$seg"
}
