import type { Rule } from "markdownlint";

import { RULE_DOCS, getHeadingLevel } from "./utils.js";

/**
 * markdownlint rule: `changeset-heading-hierarchy` (CSH001).
 *
 * Validates heading structure in changeset markdown files by inspecting
 * `atxHeading` micromark tokens for three constraints:
 *
 * 1. **No h1 headings** -- h1 is reserved for the version title generated by
 *    the changelog formatter.
 * 2. **Start at h2** -- the first heading in a changeset must be h2.
 * 3. **No depth skips** -- heading levels must increase sequentially
 *    (h2 then h3, not h2 then h4).
 *
 * @remarks
 * This rule mirrors the remark-lint rule `remarkLintHeadingHierarchy` but uses
 * markdownlint's micromark token API so it can run inside markdownlint-cli2 and
 * the VS Code markdownlint extension.
 *
 * @example
 * ```json
 * {
 *   "changeset-heading-hierarchy": true
 * }
 * ```
 *
 * @see {@link https://github.com/savvy-web/changesets/blob/main/docs/rules/CSH001.md | CSH001 rule documentation}
 * @see `src/remark/rules/heading-hierarchy.ts` for the corresponding remark-lint rule
 *
 * @public
 */
export const HeadingHierarchyRule: Rule = {
	names: ["changeset-heading-hierarchy", "CSH001"],
	description: "Heading hierarchy must start at h2 with no h1 or depth skips",
	tags: ["changeset"],
	parser: "micromark",
	function: function CSH001(params, onError) {
		let prevDepth = 0;

		for (const token of params.parsers.micromark.tokens) {
			if (token.type !== "atxHeading") {
				continue;
			}

			const depth = getHeadingLevel(token);

			if (depth === 1) {
				onError({
					lineNumber: token.startLine,
					detail: `h1 headings are not allowed in changeset files. Use h2 (##) for top-level sections like "## Features" or "## Bug Fixes". h1 is reserved for the version title generated by the changelog formatter. See: ${RULE_DOCS.CSH001}`,
				});
				continue;
			}

			if (prevDepth > 0 && depth > prevDepth + 1) {
				onError({
					lineNumber: token.startLine,
					detail: `Heading level skipped: expected h${prevDepth + 1} or lower, found h${depth}. Headings must increase sequentially (h2 → h3 → h4). Add the missing intermediate level or reduce this heading's depth. See: ${RULE_DOCS.CSH001}`,
				});
			}

			prevDepth = depth;
		}
	},
};
