/**
 * lint-staged configuration
 * Generated by savvy lint init
 *
 * The preset's ShellScripts handler strips the executable bit from staged
 * .sh files (chmod -x). Plugin hook scripts therefore commit as 100644 by
 * design — they are always invoked via `bash <script>` (hooks.json, the bats
 * runner), never executed directly, so the exec bit is unnecessary and
 * normalizing it keeps diffs clean. Not mode drift; do not "fix" it.
 *
 * plugin/builds/ is generated by pluginfinity and compared byte for byte by
 * `pluginfinity build --check`, so the writing formatters (Biome, markdownlint)
 * stay off it. The chmod -x handler deliberately still covers it: stripping the
 * exec bit from a built copy and its source in the same commit keeps the two
 * modes equal, which is what --check compares.
 */
import { Biome, Preset } from "@savvy-web/silk/lint";

const PLUGIN_BUILDS = "plugin/builds/";

export default Preset.silk({
	biome: { exclude: [...Biome.defaultExcludes, PLUGIN_BUILDS] },
	markdown: { exclude: [PLUGIN_BUILDS] },
});
