/**
 * lint-staged configuration
 * Generated by savvy lint init
 *
 * The preset's ShellScripts handler strips the executable bit from staged
 * .sh files (chmod -x). Plugin hook scripts therefore commit as 100644 by
 * design — they are always invoked via `bash <script>` (hooks.json, the bats
 * runner), never executed directly, so the exec bit is unnecessary and
 * normalizing it keeps diffs clean. Not mode drift; do not "fix" it.
 */
import { Preset } from "@savvy-web/silk/lint";

export default Preset.silk();
