/**
 * Byte-parity against the ORIGINAL implementation — the acceptance bar for
 * the savvy-web/systems#419 extraction.
 *
 * `fixtures/pr-body/expected.json` was generated by running
 * `silk-release-action/src/utils/pr-body.ts` (at the commit recorded inside
 * the fixture) over the shared case matrix in `cases.ts`. Live release-PR
 * bodies were written by that implementation, so any divergence here is a
 * wire-format break for open PRs. If a case fails, the EXTRACTION is wrong —
 * fix the extraction, never the fixture.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ManagedPrBody } from "../../src/pr-body/body.js";
import { buildCases, roundTripCases } from "./cases.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = join(here, "..", "fixtures", "pr-body", "expected.json");

interface ExpectedFixture {
	readonly source: string;
	readonly commit: string;
	readonly build: Record<string, string>;
	readonly roundTrip: Record<string, string>;
}

const expected = JSON.parse(readFileSync(fixturePath, "utf8")) as ExpectedFixture;

describe("byte parity with silk-release-action's pr-body.ts", () => {
	it("control: the fixture was found and covers every case", () => {
		// A silently-empty or truncated fixture would green every comparison.
		expect(expected.source).toBe("silk-release-action/src/utils/pr-body.ts");
		expect(expected.commit).toMatch(/^[0-9a-f]{40}$/);
		expect(Object.keys(expected.build)).toHaveLength(buildCases.length);
		expect(Object.keys(expected.roundTrip)).toHaveLength(roundTripCases.length);
		expect(buildCases.length).toBeGreaterThanOrEqual(8);
		expect(roundTripCases.length).toBeGreaterThanOrEqual(2);
	});

	for (const testCase of buildCases) {
		it(`build: ${testCase.name}`, () => {
			const fixture = expected.build[testCase.name];
			expect(fixture, `no fixture for case "${testCase.name}" — regenerate expected.json`).toBeDefined();
			expect(ManagedPrBody.build(testCase.options)).toBe(fixture);
		});
	}

	for (const testCase of roundTripCases) {
		it(`round-trip: ${testCase.name}`, () => {
			const fixture = expected.roundTrip[testCase.name];
			expect(fixture, `no fixture for case "${testCase.name}" — regenerate expected.json`).toBeDefined();

			// The exact loop update-release-branch.ts drives the original with —
			// see cases.ts for the contract shared with the fixture generator.
			let current = testCase.initial;
			for (const step of testCase.steps) {
				const managed = ManagedPrBody.build({
					...step,
					summary: ManagedPrBody.extractSummary(current),
					priorBody: current,
				});
				current = ManagedPrBody.upsert(current, managed);
			}
			expect(current).toBe(fixture);
		});
	}
});
