name: Test
on:
  push:
    branches: [main, "feat/**"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Runtime
        uses: savvy-web/workflow-runtime-action@main

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
