/**
 * Remark-lint rule: changeset-heading-hierarchy (CSH001)
 *
 * Validates heading structure in changeset files.
 *
 * @remarks
 * This rule enforces three constraints on heading levels:
 *
 * - **No h1 headings** -- h1 is reserved for the version title generated by
 *   the changelog formatter. Changeset files must use h2 (`##`) for top-level
 *   sections.
 * - **Headings must start at h2** -- the first heading in the document must be
 *   depth 2, not depth 3 or deeper.
 * - **No depth skips** -- heading levels must increase sequentially. For
 *   example, h2 followed by h4 (skipping h3) is a violation.
 *
 * The rule ID registered with unified-lint-rule is
 * `"remark-lint:changeset-heading-hierarchy"`.
 *
 * @example
 * ```typescript
 * import { HeadingHierarchyRule } from "\@savvy-web/changesets/remark";
 * import remarkParse from "remark-parse";
 * import { unified } from "unified";
 * import { VFile } from "vfile";
 *
 * const processor = unified().use(remarkParse).use(HeadingHierarchyRule);
 *
 * // Valid: sequential heading depths
 * const valid = processor.processSync(new VFile("## Features\n\n### Sub-section\n"));
 * console.log(valid.messages.length); // 0
 *
 * // Invalid: h1 heading
 * const invalid = processor.processSync(new VFile("# Title\n"));
 * console.log(invalid.messages[0].reason); // "h1 headings are not allowed..."
 * ```
 *
 * @see {@link https://github.com/savvy-web/changesets/blob/main/docs/rules/CSH001.md | CSH001 rule documentation}
 * @see {@link RequiredSectionsRule} for validating that h2 headings match known categories
 * @see {@link ContentStructureRule} for validating section content quality
 *
 * @public
 */

import type { Heading, Root } from "mdast";
import { lintRule } from "unified-lint-rule";
import { visit } from "unist-util-visit";
import { RULE_DOCS } from "../../constants.js";

export const HeadingHierarchyRule = lintRule("remark-lint:changeset-heading-hierarchy", (tree: Root, file) => {
	let prevDepth = 0;

	visit(tree, "heading", (node: Heading) => {
		if (node.depth === 1) {
			file.message(
				`h1 headings are not allowed in changeset files. Use h2 (##) for top-level sections like "## Features" or "## Bug Fixes". h1 is reserved for the version title generated by the changelog formatter. See: ${RULE_DOCS.CSH001}`,
				node,
			);
			return;
		}

		if (prevDepth > 0 && node.depth > prevDepth + 1) {
			file.message(
				`Heading level skipped: expected h${prevDepth + 1} or lower, found h${node.depth}. Headings must increase sequentially (h2 → h3 → h4). Add the missing intermediate level or reduce this heading's depth. See: ${RULE_DOCS.CSH001}`,
				node,
			);
		}

		prevDepth = node.depth;
	});
});
